// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE FIELD-COVERAGE CLASSIFIER, behind one function: [`classify`].
//!
//! The PATH SOURCE is the wire locks, `testing/llm-conformance/wire/<dialect>.wire.json`,
//! generated by `cargo xtask dialect wire --write` from the provider specs pinned by digest. Every
//! path of every direction (request, response, stream) is one field id,
//! `<dialect>/<direction>/<path>`, and each one is in exactly one state:
//!
//! * `carried <test_fn>` or `waived <YYYY-MM-DD> <reason>` in `qa/field-coverage.status`;
//! * else pinned in `qa/field-coverage.missing`, the ranked UNCLASSIFIED-NEW list (request fields
//!   first, then block types, stream events, response fields, stream fields).
//!
//! `qa/field-coverage.offspec` names the status ids that are real on the wire but absent from the
//! provider's spec root, each with its reason; a status id must be a lock path or OFF-SPEC.
//!
//! Self-contained (std + serde_json) so any crate's tests can include it by `#[path]`.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

pub const LOCK_DIR: &str = "testing/llm-conformance/wire";
pub const STATUS: &str = "qa/field-coverage.status";
pub const MISSING: &str = "qa/field-coverage.missing";
pub const OFFSPEC: &str = "qa/field-coverage.offspec";
pub const DIRECTIONS: [&str; 3] = ["request", "response", "stream"];

/// The ranking tiers of the UNCLASSIFIED-NEW list, in order.
pub const TIERS: [&str; 5] = [
    "request fields",
    "block types",
    "stream events",
    "response fields",
    "stream fields",
];

/// One field id from a wire lock. `arm` marks a union arm: a block type or a stream event.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WirePath {
    pub id: String,
    pub arm: bool,
}

impl WirePath {
    pub fn dialect(&self) -> &str {
        self.id.split('/').next().unwrap_or_default()
    }

    pub fn direction(&self) -> &str {
        self.id.split('/').nth(1).unwrap_or_default()
    }

    /// The index into [`TIERS`].
    pub fn tier(&self) -> usize {
        match (self.direction(), self.arm) {
            ("request", false) => 0,
            ("stream", true) => 2,
            (_, true) => 1,
            ("response", false) => 3,
            _ => 4,
        }
    }

    fn rank_key(&self) -> (usize, usize, &str) {
        let path = self.id.splitn(3, '/').nth(2).unwrap_or_default();
        (self.tier(), path.matches('.').count(), self.id.as_str())
    }
}

/// One declared status: `carried <test_fn>` or `waived <date> <reason>`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Status {
    Carried { test: String },
    Waived { date: String, reason: String },
}

pub struct Coverage {
    /// Every wire path, ranked.
    pub wire: Vec<WirePath>,
    pub status: BTreeMap<String, Status>,
    pub offspec: BTreeMap<String, String>,
    /// `qa/field-coverage.missing`, in file order.
    pub pinned: Vec<String>,
}

impl Coverage {
    /// Every wire path neither carried nor waived, ranked: this is what `.missing` must equal.
    pub fn unclassified(&self) -> Vec<&WirePath> {
        self.wire
            .iter()
            .filter(|w| !self.status.contains_key(&w.id))
            .collect()
    }

    pub fn ids(&self) -> BTreeSet<&str> {
        self.wire.iter().map(|w| w.id.as_str()).collect()
    }
}

pub fn repo_root() -> PathBuf {
    let mut dir = Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf();
    while !dir.join(STATUS).is_file() {
        assert!(dir.pop(), "no ancestor of the crate holds {STATUS}");
    }
    dir
}

fn read(rel: &str) -> String {
    let p = repo_root().join(rel);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("cannot read {}: {e}", p.display()))
}

fn lines(rel: &str) -> impl Iterator<Item = (usize, String)> {
    read(rel)
        .lines()
        .enumerate()
        .map(|(i, l)| (i + 1, l.trim().to_string()))
        .filter(|(_, l)| !l.is_empty() && !l.starts_with('#'))
        .collect::<Vec<_>>()
        .into_iter()
}

/// Every path of every wire lock, ranked. An empty lock set is a failure, never zero fields.
pub fn wire_paths() -> Vec<WirePath> {
    let dir = repo_root().join(LOCK_DIR);
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot list {}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.to_string_lossy().ends_with(".wire.json"))
        .collect();
    files.sort();
    assert!(
        !files.is_empty(),
        "no wire lock under {LOCK_DIR}: a coverage gate over nothing is not a gate. Run cargo \
         xtask dialect wire --write all"
    );
    let mut out = Vec::new();
    for f in files {
        let text = std::fs::read_to_string(&f).expect("lock readable");
        let doc: serde_json::Value = serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("{} is not JSON: {e}", f.display()));
        let dialect = doc["dialect"].as_str().expect("a lock names its dialect");
        for dir in DIRECTIONS {
            let Some(paths) = doc.get(dir).and_then(|d| d.as_object()) else {
                continue;
            };
            for (p, e) in paths {
                out.push(WirePath {
                    id: format!("{dialect}/{dir}/{p}"),
                    arm: e.get("arm") == Some(&serde_json::Value::Bool(true)),
                });
            }
        }
    }
    out.sort_by(|a, b| a.rank_key().cmp(&b.rank_key()));
    out
}

pub fn parse_status() -> BTreeMap<String, Status> {
    let mut out = BTreeMap::new();
    for (lineno, line) in lines(STATUS) {
        // `rsplit_once(" = ")`: a field id legitimately CONTAINS `=` (`content[].type=text.text`),
        // so the separator is the spaced ` = `, and the LAST one wins.
        let (id, rest) = line
            .rsplit_once(" = ")
            .unwrap_or_else(|| panic!("{STATUS}:{lineno}: no ` = ` separator in {line:?}"));
        let id = id.trim().to_string();
        assert!(
            !id.contains('*') && !id.contains('?'),
            "{STATUS}:{lineno}: wildcards are forbidden — a glob waiver is how a whole surface \
             disappears in one line"
        );
        let rest = rest.trim();
        let status = if let Some(test) = rest.strip_prefix("carried ") {
            let test = test.trim();
            assert!(
                !test.is_empty(),
                "{STATUS}:{lineno}: `carried` must name the test that proves it"
            );
            Status::Carried {
                test: test.to_string(),
            }
        } else if let Some(w) = rest.strip_prefix("waived ") {
            let (date, reason) = w
                .trim()
                .split_once(' ')
                .unwrap_or_else(|| panic!("{STATUS}:{lineno}: `waived` needs a date AND a reason"));
            assert!(
                date.len() == 10 && date.chars().filter(|c| *c == '-').count() == 2,
                "{STATUS}:{lineno}: waiver date must be YYYY-MM-DD, got {date:?}"
            );
            assert!(
                reason.trim().len() >= 20,
                "{STATUS}:{lineno}: a waiver reason must be something a customer could read, got \
                 {reason:?}"
            );
            Status::Waived {
                date: date.to_string(),
                reason: reason.trim().to_string(),
            }
        } else {
            panic!(
                "{STATUS}:{lineno}: state must be `carried <test>` or `waived <YYYY-MM-DD> \
                 <reason>`, got {rest:?}"
            );
        };
        assert!(
            out.insert(id.clone(), status).is_none(),
            "{STATUS}: duplicate entry for {id}"
        );
    }
    out
}

pub fn parse_offspec() -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for (lineno, line) in lines(OFFSPEC) {
        let (id, why) = line
            .split_once(" = ")
            .unwrap_or_else(|| panic!("{OFFSPEC}:{lineno}: `<field-id> = <reason>`, got {line:?}"));
        assert!(
            why.trim().len() >= 20,
            "{OFFSPEC}:{lineno}: an OFF-SPEC reason must say why the wire has what the spec lacks"
        );
        assert!(
            out.insert(id.trim().to_string(), why.trim().to_string())
                .is_none(),
            "{OFFSPEC}: duplicate entry for {id}"
        );
    }
    out
}

/// THE ONE FUNCTION: every wire path, its declared status, the OFF-SPEC ids and the pinned list.
pub fn classify() -> Coverage {
    Coverage {
        wire: wire_paths(),
        status: parse_status(),
        offspec: parse_offspec(),
        pinned: lines(MISSING).map(|(_, l)| l).collect(),
    }
}
