// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors
//
// THE TEST-LINKED PLANE TABLE (SEAM-T, N02 ruling). This crate's cross-plane integration tests
// (`tests/*_cross_plane.rs` and their siblings) need the real planes installed, but "a plugin tests
// itself; the kernel never tests or names a plugin" — so their sources name no plane crate.
// `[package.metadata.busbar] test-linked = [...]` in Cargo.toml lists the linked dev-dependency
// crates as DATA; this script turns that list into `$OUT_DIR/test_linked.rs` (`extern crate X as _;`
// per crate plus one static array of each crate's `testkit::TEST_SEAM` entry), which
// `tests/linked/mod.rs` includes and loops. The tests then address each plane by what its
// declaration states (the section it owns, the fallback flag), read back from the registry.
//
// The production library never includes the file: only the integration-test targets, which link
// the listed crates as dev-dependencies, do. Same generator shape as busbar-core-admin's build.rs.

use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let manifest = Path::new(&manifest_dir).join("Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = std::fs::read_to_string(&manifest).expect("read Cargo.toml");
    let crates = metadata_list(&text, "package.metadata.busbar", "test-linked");
    let code = linked_table(
        &crates,
        "TEST_LINKED",
        "busbar_kernel::test_support::seam::TestPlaneSeam",
        "testkit::TEST_SEAM",
    );
    std::fs::write(Path::new(&out_dir).join("test_linked.rs"), code).expect("write test_linked.rs");
    // THE KIND FIXTURES: `test-fixtures` rows read `<kind>=<crate>`; each becomes
    // `BUSBAR_FIXTURE_<KIND>` = the crate's cdylib file stem, for `test_support` to `env!`.
    for row in metadata_list(&text, "package.metadata.busbar", "test-fixtures") {
        let (kind, krate) = row
            .split_once('=')
            .expect("a test-fixtures row reads <kind>=<crate>");
        let stem = krate.replace('-', "_");
        println!(
            "cargo:rustc-env=BUSBAR_FIXTURE_{}={stem}",
            kind.to_uppercase()
        );
    }
}

/// The string array `key = [...]` under the `[table]` header of a Cargo manifest. Deliberately not a
/// TOML parser (a build script with no dependencies): the array may span lines, entries are
/// double-quoted crate names. An absent or empty list is a build failure, never an empty table — an
/// empty table would silently install nothing and the tests would read an empty roster.
fn metadata_list(manifest: &str, table: &str, key: &str) -> Vec<String> {
    let header = format!("[{table}]");
    let mut in_table = false;
    let mut collecting = false;
    let mut body = String::new();
    for line in manifest.lines() {
        let code = line.split('#').next().unwrap_or("").trim();
        if !collecting && code.starts_with('[') {
            in_table = code == header;
            continue;
        }
        if collecting {
            body.push_str(code);
        } else if in_table {
            if let Some((k, v)) = code.split_once('=') {
                if k.trim() == key {
                    collecting = true;
                    body.push_str(v.trim());
                }
            }
        }
        if collecting && body.contains(']') {
            break;
        }
    }
    let list: Vec<String> = body
        .trim()
        .trim_start_matches('[')
        .split(']')
        .next()
        .unwrap_or("")
        .split(',')
        .map(|s| s.trim().trim_matches('"').to_string())
        .filter(|s| !s.is_empty())
        .collect();
    assert!(
        !list.is_empty(),
        "Cargo.toml: `{key}` under `{header}` is missing or empty"
    );
    list
}

/// `extern crate <ident> as _;` for every listed crate, then
/// `static <name>: &[<ty>] = &[<ident>::<entry>, ...];` in list order.
fn linked_table(crates: &[String], name: &str, ty: &str, entry: &str) -> String {
    let idents: Vec<String> = crates.iter().map(|c| c.replace('-', "_")).collect();
    let mut out = String::from("// @generated by build.rs from Cargo.toml metadata.\n");
    for id in &idents {
        out.push_str(&format!("extern crate {id} as _;\n"));
    }
    out.push_str(&format!("static {name}: &[{ty}] = &[\n"));
    for id in &idents {
        out.push_str(&format!("    {id}::{entry},\n"));
    }
    out.push_str("];\n");
    out
}
