// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/anthropic.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Cond, Dir, Field, Handled, Slot, Table, Word, row};

/// Row group `sampling`.
pub(crate) const ROWS_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, Codec::Plain).clamp(0.0, 1.0, "clamping temperature to Anthropic's [0.0, 1.0] range; the requested value was outside it (e.g. an OpenAI/Responses value up to 2.0) and would 422 — the forwarded value diverges from the caller's request", true).drop_if(Cond::Thinking, "omitting temperature on Anthropic egress: not compatible with thinking", true),
    row(&["top_p"], Slot::TopP, Codec::Plain).drop_if(Cond::Thinking, "omitting top_p on Anthropic egress: not compatible with thinking", true),
    row(&["top_k"], Slot::TopK, Codec::Plain).drop_if(Cond::Thinking, "omitting top_k on Anthropic egress: not compatible with thinking", true),
    row(&["stop_sequences"], Slot::Stop, Codec::Plain),
];

/// Row group `structure`.
pub(crate) const ROWS_STRUCTURE: &[Field] = &[
    row(&["max_tokens"], Slot::Structure, Codec::Prim("max_output")),
    row(&["messages"], Slot::Structure, Codec::Prim("messages")),
    row(&["model"], Slot::Structure, Codec::Prim("model")),
    row(&["stream"], Slot::Structure, Codec::Prim("stream")),
    row(&["system"], Slot::Structure, Codec::Prim("system")),
    row(&["tool_choice"], Slot::Structure, Codec::Prim("tool_choice")),
    row(&["tools"], Slot::Structure, Codec::Prim("tools")),
];

/// Row group `tier`.
pub(crate) const ROWS_TIER: &[Field] = &[
    row(&["service_tier"], Slot::ServiceTier, Codec::Words(WORDS_SERVICE_TIER)).park(),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_STRUCTURE, ROWS_SAMPLING, ROWS_TIER];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::FrequencyPenalty, Handled::Warn("dropping frequency_penalty on Anthropic egress: the Messages API models no such sampling control (lossy-by-target)", true)),
    (Slot::PresencePenalty, Handled::Warn("dropping presence_penalty on Anthropic egress: the Messages API models no such sampling control (lossy-by-target)", true)),
    (Slot::Seed, Handled::Warn("dropping seed on Anthropic egress: the Messages API models no deterministic-sampling seed (lossy-by-target)", true)),
    (Slot::N, Handled::Warn("dropping n on Anthropic egress: the Messages API returns a single completion and models no candidate-count parameter (lossy-by-target)", true)),
    (Slot::ServiceTier, Handled::Warn("dropping service_tier on Anthropic egress: Anthropic offers only auto /                      standard_only capacity (lossy-by-target)", true)),
];

/// The warn for every other derived drop.
pub(crate) const DROP_WARN: crate::codec::dialect::DropWarn =
    crate::codec::dialect::DropWarn::Parameter("dropping {slot} on Anthropic egress: the Messages API has no such request                      member (lossy-by-target)");

/// Word table `service_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_SERVICE_TIER: &[Word] = &[
    ("auto", "auto", Dir::Both),
    ("standard_only", "default", Dir::Both),
    ("auto", "priority", Dir::Write),
];
