// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/anthropic.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Cond, Field, Slot, Table, row};

/// Row group `sampling`.
pub(crate) const ROWS_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, Codec::Plain).clamp(0.0, 1.0, "clamping temperature to Anthropic's [0.0, 1.0] range; the requested value was outside it (e.g. an OpenAI/Responses value up to 2.0) and would 422 — the forwarded value diverges from the caller's request", true).drop_if(Cond::Thinking, "omitting temperature on Anthropic egress: not compatible with thinking", true),
    row(&["top_p"], Slot::TopP, Codec::Plain).drop_if(Cond::Thinking, "omitting top_p on Anthropic egress: not compatible with thinking", true),
    row(&["top_k"], Slot::TopK, Codec::Plain).drop_if(Cond::Thinking, "omitting top_k on Anthropic egress: not compatible with thinking", true),
    row(&["stop_sequences"], Slot::Stop, Codec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_SAMPLING];
