// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod zcfacts {


pub enum FactsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Facts<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Facts<'a> {
  type Inner = Facts<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Facts<'a> {
  pub const VT_VERB: ::flatbuffers::VOffsetT = 4;
  pub const VT_WANTS_STREAM: ::flatbuffers::VOffsetT = 6;
  pub const VT_END_USER: ::flatbuffers::VOffsetT = 8;
  pub const VT_SHAPE: ::flatbuffers::VOffsetT = 10;
  pub const VT_MODEL: ::flatbuffers::VOffsetT = 12;
  pub const VT_N_PARTS: ::flatbuffers::VOffsetT = 14;
  pub const VT_BODY: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Facts { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FactsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Facts<'bldr>> {
    let mut builder = FactsBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    builder.add_n_parts(args.n_parts);
    if let Some(x) = args.model { builder.add_model(x); }
    if let Some(x) = args.shape { builder.add_shape(x); }
    if let Some(x) = args.end_user { builder.add_end_user(x); }
    if let Some(x) = args.verb { builder.add_verb(x); }
    builder.add_wants_stream(args.wants_stream);
    builder.finish()
  }


  #[inline]
  pub fn verb(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Facts::VT_VERB, None)}
  }
  #[inline]
  pub fn wants_stream(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Facts::VT_WANTS_STREAM, Some(false)).unwrap()}
  }
  #[inline]
  pub fn end_user(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Facts::VT_END_USER, None)}
  }
  #[inline]
  pub fn shape(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Facts::VT_SHAPE, None)}
  }
  #[inline]
  pub fn model(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Facts::VT_MODEL, None)}
  }
  #[inline]
  pub fn n_parts(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Facts::VT_N_PARTS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn body(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Facts::VT_BODY, None)}
  }
}

impl ::flatbuffers::Verifiable for Facts<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("verb", Self::VT_VERB, false)?
     .visit_field::<bool>("wants_stream", Self::VT_WANTS_STREAM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("end_user", Self::VT_END_USER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("shape", Self::VT_SHAPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("model", Self::VT_MODEL, false)?
     .visit_field::<u32>("n_parts", Self::VT_N_PARTS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("body", Self::VT_BODY, false)?
     .finish();
    Ok(())
  }
}
pub struct FactsArgs<'a> {
    pub verb: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub wants_stream: bool,
    pub end_user: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub shape: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub model: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub n_parts: u32,
    pub body: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for FactsArgs<'a> {
  #[inline]
  fn default() -> Self {
    FactsArgs {
      verb: None,
      wants_stream: false,
      end_user: None,
      shape: None,
      model: None,
      n_parts: 0,
      body: None,
    }
  }
}

pub struct FactsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FactsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_verb(&mut self, verb: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Facts::VT_VERB, verb);
  }
  #[inline]
  pub fn add_wants_stream(&mut self, wants_stream: bool) {
    self.fbb_.push_slot::<bool>(Facts::VT_WANTS_STREAM, wants_stream, false);
  }
  #[inline]
  pub fn add_end_user(&mut self, end_user: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Facts::VT_END_USER, end_user);
  }
  #[inline]
  pub fn add_shape(&mut self, shape: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Facts::VT_SHAPE, shape);
  }
  #[inline]
  pub fn add_model(&mut self, model: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Facts::VT_MODEL, model);
  }
  #[inline]
  pub fn add_n_parts(&mut self, n_parts: u32) {
    self.fbb_.push_slot::<u32>(Facts::VT_N_PARTS, n_parts, 0);
  }
  #[inline]
  pub fn add_body(&mut self, body: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Facts::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FactsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FactsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Facts<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Facts<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Facts");
      ds.field("verb", &self.verb());
      ds.field("wants_stream", &self.wants_stream());
      ds.field("end_user", &self.end_user());
      ds.field("shape", &self.shape());
      ds.field("model", &self.model());
      ds.field("n_parts", &self.n_parts());
      ds.field("body", &self.body());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Facts`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_facts_unchecked`.
pub fn root_as_facts(buf: &[u8]) -> Result<Facts<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Facts>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Facts` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_facts_unchecked`.
pub fn size_prefixed_root_as_facts(buf: &[u8]) -> Result<Facts<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Facts>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Facts` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_facts_unchecked`.
pub fn root_as_facts_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Facts<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Facts<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Facts` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_facts_unchecked`.
pub fn size_prefixed_root_as_facts_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Facts<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Facts<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Facts and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Facts`.
pub unsafe fn root_as_facts_unchecked(buf: &[u8]) -> Facts<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Facts>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Facts and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Facts`.
pub unsafe fn size_prefixed_root_as_facts_unchecked(buf: &[u8]) -> Facts<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Facts>(buf) }
}
#[inline]
pub fn finish_facts_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Facts<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_facts_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Facts<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod zcfacts

