// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod zcir {


pub enum TextBlockOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TextBlock<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for TextBlock<'a> {
  type Inner = TextBlock<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TextBlock<'a> {
  pub const VT_TEXT: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    TextBlock { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TextBlockArgs<'args>
  ) -> ::flatbuffers::WIPOffset<TextBlock<'bldr>> {
    let mut builder = TextBlockBuilder::new(_fbb);
    if let Some(x) = args.text { builder.add_text(x); }
    builder.finish()
  }


  #[inline]
  pub fn text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(TextBlock::VT_TEXT, None)}
  }
}

impl ::flatbuffers::Verifiable for TextBlock<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct TextBlockArgs<'a> {
    pub text: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TextBlockArgs<'a> {
  #[inline]
  fn default() -> Self {
    TextBlockArgs {
      text: None,
    }
  }
}

pub struct TextBlockBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TextBlockBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_text(&mut self, text: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(TextBlock::VT_TEXT, text);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TextBlockBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TextBlockBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<TextBlock<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for TextBlock<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("TextBlock");
      ds.field("text", &self.text());
      ds.finish()
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Message<'a> {
  pub const VT_ROLE: ::flatbuffers::VOffsetT = 4;
  pub const VT_CONTENT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.content { builder.add_content(x); }
    if let Some(x) = args.role { builder.add_role(x); }
    builder.finish()
  }


  #[inline]
  pub fn role(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Message::VT_ROLE, None)}
  }
  #[inline]
  pub fn content(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TextBlock<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TextBlock>>>>(Message::VT_CONTENT, None)}
  }
}

impl ::flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("role", Self::VT_ROLE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<TextBlock>>>>("content", Self::VT_CONTENT, false)?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs<'a> {
    pub role: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub content: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TextBlock<'a>>>>>,
}
impl<'a> Default for MessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      role: None,
      content: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_role(&mut self, role: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Message::VT_ROLE, role);
  }
  #[inline]
  pub fn add_content(&mut self, content: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<TextBlock<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Message::VT_CONTENT, content);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("role", &self.role());
      ds.field("content", &self.content());
      ds.finish()
  }
}
pub enum ToolOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Tool<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Tool<'a> {
  type Inner = Tool<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Tool<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 6;
  pub const VT_INPUT_SCHEMA: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Tool { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ToolArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Tool<'bldr>> {
    let mut builder = ToolBuilder::new(_fbb);
    if let Some(x) = args.input_schema { builder.add_input_schema(x); }
    if let Some(x) = args.description { builder.add_description(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Tool::VT_NAME, None)}
  }
  #[inline]
  pub fn description(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Tool::VT_DESCRIPTION, None)}
  }
  #[inline]
  pub fn input_schema(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Tool::VT_INPUT_SCHEMA, None)}
  }
}

impl ::flatbuffers::Verifiable for Tool<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("description", Self::VT_DESCRIPTION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("input_schema", Self::VT_INPUT_SCHEMA, false)?
     .finish();
    Ok(())
  }
}
pub struct ToolArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub description: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub input_schema: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ToolArgs<'a> {
  #[inline]
  fn default() -> Self {
    ToolArgs {
      name: None,
      description: None,
      input_schema: None,
    }
  }
}

pub struct ToolBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ToolBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Tool::VT_NAME, name);
  }
  #[inline]
  pub fn add_description(&mut self, description: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Tool::VT_DESCRIPTION, description);
  }
  #[inline]
  pub fn add_input_schema(&mut self, input_schema: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Tool::VT_INPUT_SCHEMA, input_schema);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ToolBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ToolBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Tool<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Tool<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Tool");
      ds.field("name", &self.name());
      ds.field("description", &self.description());
      ds.field("input_schema", &self.input_schema());
      ds.finish()
  }
}
pub enum ChatReqOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChatReq<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ChatReq<'a> {
  type Inner = ChatReq<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ChatReq<'a> {
  pub const VT_MODEL: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAX_TOKENS: ::flatbuffers::VOffsetT = 6;
  pub const VT_STREAM: ::flatbuffers::VOffsetT = 8;
  pub const VT_SYSTEM: ::flatbuffers::VOffsetT = 10;
  pub const VT_MESSAGES: ::flatbuffers::VOffsetT = 12;
  pub const VT_TOOLS: ::flatbuffers::VOffsetT = 14;
  pub const VT_END_USER: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ChatReq { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChatReqArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ChatReq<'bldr>> {
    let mut builder = ChatReqBuilder::new(_fbb);
    if let Some(x) = args.end_user { builder.add_end_user(x); }
    if let Some(x) = args.tools { builder.add_tools(x); }
    if let Some(x) = args.messages { builder.add_messages(x); }
    if let Some(x) = args.system { builder.add_system(x); }
    builder.add_max_tokens(args.max_tokens);
    if let Some(x) = args.model { builder.add_model(x); }
    builder.add_stream(args.stream);
    builder.finish()
  }


  #[inline]
  pub fn model(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ChatReq::VT_MODEL, None)}
  }
  #[inline]
  pub fn max_tokens(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ChatReq::VT_MAX_TOKENS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn stream(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ChatReq::VT_STREAM, Some(false)).unwrap()}
  }
  #[inline]
  pub fn system(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ChatReq::VT_SYSTEM, None)}
  }
  #[inline]
  pub fn messages(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Message<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Message>>>>(ChatReq::VT_MESSAGES, None)}
  }
  #[inline]
  pub fn tools(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tool<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tool>>>>(ChatReq::VT_TOOLS, None)}
  }
  #[inline]
  pub fn end_user(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ChatReq::VT_END_USER, None)}
  }
}

impl ::flatbuffers::Verifiable for ChatReq<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("model", Self::VT_MODEL, false)?
     .visit_field::<u32>("max_tokens", Self::VT_MAX_TOKENS, false)?
     .visit_field::<bool>("stream", Self::VT_STREAM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("system", Self::VT_SYSTEM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Message>>>>("messages", Self::VT_MESSAGES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Tool>>>>("tools", Self::VT_TOOLS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("end_user", Self::VT_END_USER, false)?
     .finish();
    Ok(())
  }
}
pub struct ChatReqArgs<'a> {
    pub model: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub max_tokens: u32,
    pub stream: bool,
    pub system: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub messages: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Message<'a>>>>>,
    pub tools: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tool<'a>>>>>,
    pub end_user: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ChatReqArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChatReqArgs {
      model: None,
      max_tokens: 0,
      stream: false,
      system: None,
      messages: None,
      tools: None,
      end_user: None,
    }
  }
}

pub struct ChatReqBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ChatReqBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_model(&mut self, model: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ChatReq::VT_MODEL, model);
  }
  #[inline]
  pub fn add_max_tokens(&mut self, max_tokens: u32) {
    self.fbb_.push_slot::<u32>(ChatReq::VT_MAX_TOKENS, max_tokens, 0);
  }
  #[inline]
  pub fn add_stream(&mut self, stream: bool) {
    self.fbb_.push_slot::<bool>(ChatReq::VT_STREAM, stream, false);
  }
  #[inline]
  pub fn add_system(&mut self, system: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ChatReq::VT_SYSTEM, system);
  }
  #[inline]
  pub fn add_messages(&mut self, messages: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Message<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ChatReq::VT_MESSAGES, messages);
  }
  #[inline]
  pub fn add_tools(&mut self, tools: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Tool<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ChatReq::VT_TOOLS, tools);
  }
  #[inline]
  pub fn add_end_user(&mut self, end_user: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ChatReq::VT_END_USER, end_user);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ChatReqBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChatReqBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ChatReq<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ChatReq<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ChatReq");
      ds.field("model", &self.model());
      ds.field("max_tokens", &self.max_tokens());
      ds.field("stream", &self.stream());
      ds.field("system", &self.system());
      ds.field("messages", &self.messages());
      ds.field("tools", &self.tools());
      ds.field("end_user", &self.end_user());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ChatReq`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chat_req_unchecked`.
pub fn root_as_chat_req(buf: &[u8]) -> Result<ChatReq<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ChatReq>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ChatReq` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_chat_req_unchecked`.
pub fn size_prefixed_root_as_chat_req(buf: &[u8]) -> Result<ChatReq<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ChatReq>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ChatReq` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chat_req_unchecked`.
pub fn root_as_chat_req_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChatReq<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ChatReq<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ChatReq` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_chat_req_unchecked`.
pub fn size_prefixed_root_as_chat_req_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChatReq<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ChatReq<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ChatReq and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ChatReq`.
pub unsafe fn root_as_chat_req_unchecked(buf: &[u8]) -> ChatReq<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ChatReq>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ChatReq and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ChatReq`.
pub unsafe fn size_prefixed_root_as_chat_req_unchecked(buf: &[u8]) -> ChatReq<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ChatReq>(buf) }
}
#[inline]
pub fn finish_chat_req_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ChatReq<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_chat_req_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ChatReq<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod zcir

