// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/gemini.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Field, Handled, Slot, Table, ValueCodec, row};

/// Row group `generation_config`.
pub(crate) const ROWS_GENERATION_CONFIG: &[Field] = &[
    row(&["generationConfig", "temperature"], Slot::Temperature, ValueCodec::Plain),
    row(&["generationConfig", "topP"], Slot::TopP, ValueCodec::Plain),
    row(&["generationConfig", "topK"], Slot::TopK, ValueCodec::Plain),
    row(&["generationConfig", "stopSequences"], Slot::Stop, ValueCodec::Plain).cap(5, "Gemini"),
    row(&["generationConfig", "frequencyPenalty"], Slot::FrequencyPenalty, ValueCodec::Plain),
    row(&["generationConfig", "presencePenalty"], Slot::PresencePenalty, ValueCodec::Plain),
    row(&["generationConfig", "seed"], Slot::Seed, ValueCodec::Plain),
    row(&["generationConfig", "candidateCount"], Slot::N, ValueCodec::Plain),
];

/// Row group `structure`.
pub(crate) const ROWS_STRUCTURE: &[Field] = &[
    row(&["contents"], Slot::Structure, ValueCodec::Prim("messages")),
    row(&["tools"], Slot::Structure, ValueCodec::Prim("tools")),
    row(&["systemInstruction"], Slot::Structure, ValueCodec::Prim("system")),
    row(&["model"], Slot::Structure, ValueCodec::Prim("model")),
    row(&["__busbar_gemini_json_array"], Slot::Structure, ValueCodec::Prim("json_array_shim")),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_STRUCTURE, ROWS_GENERATION_CONFIG];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::Metadata, Handled::Code("gemini_labels")),
    (Slot::OutputModalities, Handled::Code("gemini_response_modalities")),
];

/// The warn for every other derived drop.
pub(crate) const DROP_WARN: crate::codec::dialect::DropWarn =
    crate::codec::dialect::DropWarn::Control("dropping a request control on Gemini egress: generateContent has no form for it");
