// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/gemini.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Dir, Field, Handled, Slot, Table, ValueCodec, Word, row};

/// Row group `blocks`.
pub(crate) const ROWS_BLOCKS: &[Field] = &[
    row(&["contents[]", "parts[]", "inlineData", "mimeType"], Slot::Structure, ValueCodec::Prim("mime_type")),
    row(&["contents[]", "parts[]", "inlineData", "data"], Slot::Structure, ValueCodec::Prim("data")),
    row(&["contents[]", "role"], Slot::Structure, ValueCodec::Prim("role")),
    row(&["contents[]", "parts"], Slot::Structure, ValueCodec::Prim("parts")),
    row(&["generationConfig", "responseMimeType"], Slot::Structure, ValueCodec::Prim("response_mime_type")),
    row(&["generationConfig", "responseSchema"], Slot::Structure, ValueCodec::Prim("response_schema")),
    row(&["generationConfig", "responseModalities"], Slot::Structure, ValueCodec::Prim("response_modalities")),
    row(&["generationConfig", "thinkingConfig", "thinkingBudget"], Slot::Structure, ValueCodec::Prim("thinking_budget")),
    row(&["generationConfig", "thinkingConfig", "includeThoughts"], Slot::Structure, ValueCodec::Prim("include_thoughts")),
    row(&["generationConfig", "mediaResolution"], Slot::Structure, ValueCodec::Prim("media_resolution")),
    row(&["generationConfig", "speechConfig"], Slot::Structure, ValueCodec::Prim("speech_config")),
    row(&["contents[]", "parts[]", "text"], Slot::Structure, ValueCodec::Prim("text")),
    row(&["contents[]", "parts[]", "thought"], Slot::Structure, ValueCodec::Prim("thought")),
    row(&["contents[]", "parts[]", "thoughtSignature"], Slot::Structure, ValueCodec::Prim("thought_signature")),
    row(&["contents[]", "parts[]", "fileData", "fileUri"], Slot::Structure, ValueCodec::Prim("file_uri")),
    row(&["contents[]", "parts[]", "fileData", "mimeType"], Slot::Structure, ValueCodec::Prim("mime_type")),
    row(&["contents[]", "parts[]", "functionCall", "name"], Slot::Structure, ValueCodec::Prim("name")),
    row(&["contents[]", "parts[]", "functionCall", "args"], Slot::Structure, ValueCodec::Prim("args")),
    row(&["contents[]", "parts[]", "functionResponse", "name"], Slot::Structure, ValueCodec::Prim("name")),
    row(&["contents[]", "parts[]", "functionResponse", "response"], Slot::Structure, ValueCodec::Prim("response")),
    row(&["contents[]", "parts[]", "executableCode"], Slot::Structure, ValueCodec::Prim("executable_code")),
    row(&["contents[]", "parts[]", "codeExecutionResult"], Slot::Structure, ValueCodec::Prim("code_execution_result")),
];

/// Row group `generation_config`.
pub(crate) const ROWS_GENERATION_CONFIG: &[Field] = &[
    row(&["generationConfig", "temperature"], Slot::Temperature, ValueCodec::Plain),
    row(&["generationConfig", "topP"], Slot::TopP, ValueCodec::Plain),
    row(&["generationConfig", "topK"], Slot::TopK, ValueCodec::Plain),
    row(&["generationConfig", "stopSequences"], Slot::Stop, ValueCodec::Plain).cap(5, "Gemini"),
    row(&["generationConfig", "frequencyPenalty"], Slot::FrequencyPenalty, ValueCodec::Plain),
    row(&["generationConfig", "presencePenalty"], Slot::PresencePenalty, ValueCodec::Plain),
    row(&["generationConfig", "seed"], Slot::Seed, ValueCodec::Plain),
    row(&["generationConfig", "candidateCount"], Slot::N, ValueCodec::Plain),
];

/// Row group `structure`.
pub(crate) const ROWS_STRUCTURE: &[Field] = &[
    row(&["contents"], Slot::Structure, ValueCodec::Prim("messages")),
    row(&["tools"], Slot::Structure, ValueCodec::Prim("tools")),
    row(&["systemInstruction"], Slot::Structure, ValueCodec::Prim("system")),
    row(&["generationConfig", "maxOutputTokens"], Slot::Structure, ValueCodec::Prim("max_output")),
    row(&["generationConfig", "responseLogprobs"], Slot::Structure, ValueCodec::Prim("logprobs")),
    row(&["generationConfig", "logprobs"], Slot::Structure, ValueCodec::Prim("logprobs")),
    row(&["tools[]", "googleSearch"], Slot::Structure, ValueCodec::Prim("web_search")),
    row(&["model"], Slot::Structure, ValueCodec::Prim("model")),
    row(&["__busbar_gemini_json_array"], Slot::Structure, ValueCodec::Prim("json_array_shim")),
];

/// Row group `tier`.
pub(crate) const ROWS_TIER: &[Field] = &[
    row(&["serviceTier"], Slot::ServiceTier, ValueCodec::Words(WORDS_SERVICE_TIER)).park(),
    row(&["store"], Slot::Store, ValueCodec::Plain).park(),
];

/// The response wire paths this dialect carries (the drop walk's map).
pub(crate) const RESPONSE_PATHS: &[&str] = &[
    "candidates[].groundingMetadata.groundingChunks[].web.uri",
    "candidates[].groundingMetadata.groundingChunks[].web.title",
    "candidates[].safetyRatings[].category",
    "candidates[].safetyRatings[].blocked",
    "promptFeedback.safetyRatings[].category",
    "promptFeedback.safetyRatings[].blocked",
    "usageMetadata.promptTokensDetails[].modality",
    "usageMetadata.promptTokensDetails[].tokenCount",
    "usageMetadata.candidatesTokensDetails[].modality",
    "usageMetadata.candidatesTokensDetails[].tokenCount",
    "usageMetadata.cacheTokensDetails[].modality",
    "usageMetadata.cacheTokensDetails[].tokenCount",
    "usageMetadata.serviceTier",
    "usageMetadata.thoughtsTokenCount",
    "usageMetadata.promptTokenCount",
    "usageMetadata.candidatesTokenCount",
    "usageMetadata.totalTokenCount",
    "candidates[].content",
    "candidates[].finishReason",
    "candidates[].index",
    "candidates[].safetyRatings",
    "candidates[].citationMetadata",
    "candidates[].groundingMetadata",
    "candidates[].avgLogprobs",
    "candidates[].logprobsResult",
    "candidates[].tokenCount",
    "promptFeedback.blockReason",
    "promptFeedback.safetyRatings",
    "usageMetadata.cachedContentTokenCount",
    "usageMetadata.toolUsePromptTokenCount",
    "usageMetadata.promptTokensDetails",
    "modelVersion",
    "responseId",
    "candidates[].content.parts[].functionCall.name",
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_STRUCTURE, ROWS_GENERATION_CONFIG, ROWS_TIER, ROWS_BLOCKS];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::Metadata, Handled::Code("gemini_labels")),
    (Slot::OutputModalities, Handled::Code("gemini_response_modalities")),
];

/// The warn for every other derived drop.
pub(crate) const DROP_WARN: crate::codec::dialect::DropWarn =
    crate::codec::dialect::DropWarn::Control("dropping a request control on Gemini egress: generateContent has no form for it");

/// Word table `service_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_SERVICE_TIER: &[Word] = &[
    ("standard", "default", Dir::Both),
    ("flex", "flex", Dir::Both),
    ("priority", "priority", Dir::Both),
];
