// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/gemini.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Field, Slot, Table, row};

/// Row group `generation_config`.
pub(crate) const ROWS_GENERATION_CONFIG: &[Field] = &[
    row(&["generationConfig", "temperature"], Slot::Temperature, Codec::Plain),
    row(&["generationConfig", "topP"], Slot::TopP, Codec::Plain),
    row(&["generationConfig", "topK"], Slot::TopK, Codec::Plain),
    row(&["generationConfig", "stopSequences"], Slot::Stop, Codec::Plain).cap(5, "Gemini"),
    row(&["generationConfig", "frequencyPenalty"], Slot::FrequencyPenalty, Codec::Plain),
    row(&["generationConfig", "presencePenalty"], Slot::PresencePenalty, Codec::Plain),
    row(&["generationConfig", "seed"], Slot::Seed, Codec::Plain),
    row(&["generationConfig", "candidateCount"], Slot::N, Codec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_GENERATION_CONFIG];
