// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE COMPOSITION-ROOT INSTALL for the host-selection seam (loop unification, DECISIONS #28).
//!
//! The kernel-loop runners ([`run_gauntlet_via_kernel`] / [`open_gauntlet_via_kernel`]) live here in
//! the root (the only tier that sees both `busbar-kernel` and the plane engines). This module injects
//! them into the neutral per-capability-keyed registry in `busbar_kernel::plane_host` as
//! fn-pointers, mirroring `busbar_admin::install()`.
//!
//! LIVE, NOT DORMANT: [`install`] is called unconditionally at boot and FLIPS EVERY PLANE the linked
//! table puts on a kernel-loop axis (each row present only when the feature that pulls its crate is
//! on), so every `run_gauntlet[_session]` call for those planes dispatches into the kernel loop
//! through this registry. The substrate loop it replaced no longer exists; an unflipped plane runs
//! `run_gauntlet`'s inline verify-then-`drive` fallback.
//!
//! MONEY-NEUTRAL BY CONSTRUCTION, and MEASURED (item 125, 2026-09-24, pin 079a16efc): the
//! kernel-loop runner opens a ZERO hold and reports zero evidence (see `gauntlet_kernel.rs`), so
//! the plane's own metering inside `drive` stays the only money path. A build with every flip
//! commented out recorded the two diverging C3 money cells
//! (`billing|key-usage|after-upstream-down`, `billing|rate-card|history-mid-window`) byte-identical
//! to the flipped build. The per-plane money authority for a plane on the `node` axis is the root's
//! node (`root/plane_node.rs`), not this seam.

use std::future::Future;
use std::pin::Pin;

use axum::response::Response;
use busbar_kernel::plane_host::{
    register_gauntlet_runner, register_session_runner, GauntletPlane, GauntletRequest,
};

use crate::root::gauntlet_kernel::{open_gauntlet_via_kernel, run_gauntlet_via_kernel};

/// The kernel-loop one-shot runner as a `busbar_kernel::plane_host::GauntletRunner` fn-pointer:
/// the async runner boxed into the erased future the neutral seam holds.
fn kernel_one_shot<'a>(
    req: GauntletRequest<'a>,
    plane: Box<dyn GauntletPlane + 'a>,
) -> Pin<Box<dyn Future<Output = Response> + Send + 'a>> {
    Box::pin(run_gauntlet_via_kernel(req, plane))
}

/// FLIP a one-shot plane onto the unified kernel loop, by capability key. [`install`] calls it for
/// every `gauntlet-one-shot` row of the linked table. A key it is never called for runs
/// `run_gauntlet`'s inline verify-then-`drive` fallback; there is no substrate loop left to ride.
pub fn flip_one_shot_to_kernel(capability_key: &'static str) {
    register_gauntlet_runner(capability_key, kernel_one_shot);
}

/// FLIP a session (duplex) plane onto the unified kernel loop's session admit, by capability key.
/// [`install`] calls it for every `gauntlet-session` row of the linked table; a key it is never called for runs
/// `run_gauntlet_session`'s inline open-pass fallback.
pub fn flip_session_to_kernel(capability_key: &'static str) {
    register_session_runner(capability_key, open_gauntlet_via_kernel);
}

/// Install the kernel-backed runners into the host-selection seam. Called once by `main.rs` at boot,
/// AFTER the planes are registered (mirror of `busbar_admin::install()`).
///
/// Every plane the build links onto a kernel-loop axis is FLIPPED onto the unified
/// kernel loop (DECISIONS #28/#29). WHICH planes is manifest data, not a list here: a
/// `[package.metadata.busbar.linked-axes]` row carrying `gauntlet-one-shot` or `gauntlet-session`
/// puts that plane's `PLANE_DECLARATION.key` in the linked table (`LINKED.gauntlet_one_shot` /
/// `LINKED.gauntlet_session`, generated by `build.rs`), and this registers the matching kernel-loop
/// runner under each key, so the SHIPPED serving path for those planes flows through
/// `busbar_kernel::teller::run_unit[_async]` / `open_unit`. A key with no runner registered runs
/// the inline verify-then-`drive` (or open-pass) fallback in `run_gauntlet[_session]`; there is no
/// second loop to ride.
///
/// - A ONE-SHOT plane (request → response) → [`flip_one_shot_to_kernel`].
/// - A SESSION plane (open-pass admit, no one-shot `drive`) → [`flip_session_to_kernel`].
///
/// The table holds only the rows whose cargo feature is enabled, so a build that omits a plane also
/// omits its flip (and that plane's `GauntletPlane` never runs).
pub fn install() {
    for &key in crate::LINKED.gauntlet_one_shot {
        flip_one_shot_to_kernel(key);
    }
    for &key in crate::LINKED.gauntlet_session {
        flip_session_to_kernel(key);
    }
}
