//! THE ROOT LEGACY TABLE, rendered from `plugins.yaml` (BUSBAR-1.6.0.md §2: "Retired names … live in
//! the root legacy table, `[package.metadata.busbar.legacy]`, generated from `plugins.yaml`"; the
//! legacy-table ruling of 2026-10-02). `fleet sync` writes it into the root manifest; `fleet check`
//! refuses a manifest whose table is not the render.
//!
//! The rows, in order: the `legacy:` block's frozen 1.5.5 text, sorted by key; then, per entry in
//! registry order with a `retired:` list, one `retired.<kind>.<word> = "<alias>"` row per word and the
//! entry's `manifest.<alias>` / `asset.<alias>` rows. Everything between the table header and the next
//! table header is the render's.

use crate::fleet::registry::Fleet;

/// The manifest the table lives in.
pub const MANIFEST: &str = "crates/busbar/Cargo.toml";

/// The table's header.
pub const HEADER: &str = "[package.metadata.busbar.legacy]";

/// The comment the render opens the table with.
const NOTE: &str = "# THE ROOT LEGACY TABLE (BUSBAR-1.6.0.md §2), @generated by `cargo xtask fleet sync` from\n\
# plugins.yaml (`legacy:` and each entry's `retired:`); `cargo xtask fleet check` refuses an edit.\n\
# build.rs emits it as `LEGACY_ROWS`, which the root hands to the kernel before any config is read.\n";

/// The table's rows.
pub fn rows(fleet: &Fleet) -> Vec<(String, String)> {
    let mut out = fleet.legacy.clone();
    out.sort();
    for p in fleet.plugins.iter().filter(|p| !p.retired.is_empty()) {
        for word in &p.retired {
            out.push((format!("retired.{}.{word}", p.kind), p.alias.clone()));
        }
        out.push((format!("manifest.{}", p.alias), p.manifest_name.clone()));
        out.push((format!("asset.{}", p.alias), p.asset_prefix.clone()));
    }
    out
}

/// The rendered table: the header, the note and one quoted row per line.
pub fn render(fleet: &Fleet) -> String {
    let mut s = format!("{HEADER}\n{NOTE}");
    for (k, v) in rows(fleet) {
        s.push_str(&format!(
            "\"{k}\" = \"{}\"\n",
            v.replace('\\', "\\\\").replace('"', "\\\"")
        ));
    }
    s
}

/// `manifest` with its legacy table replaced by the render (appended when it has none). The table
/// runs from its header to the line before the next table header (or the end), less trailing blank
/// lines.
pub fn apply(manifest: &str, fleet: &Fleet) -> String {
    let table = render(fleet);
    let lines: Vec<&str> = manifest.lines().collect();
    let Some(start) = lines.iter().position(|l| l.trim() == HEADER) else {
        let mut s = manifest.trim_end().to_string();
        s.push_str("\n\n");
        s.push_str(&table);
        return s;
    };
    let mut end = lines[start + 1..]
        .iter()
        .position(|l| l.trim_start().starts_with('['))
        .map_or(lines.len(), |i| start + 1 + i);
    while end > start + 1 && lines[end - 1].trim().is_empty() {
        end -= 1;
    }
    let mut s = lines[..start].join("\n");
    if start > 0 {
        s.push('\n');
    }
    s.push_str(&table);
    if end < lines.len() {
        s.push('\n');
        s.push_str(&lines[end..].join("\n"));
        s.push('\n');
    }
    s
}

/// The drift `fleet check` reports: `None` when the manifest's table is the render.
pub fn drift(manifest: &str, fleet: &Fleet) -> Option<String> {
    (apply(manifest, fleet) != manifest).then(|| {
        format!(
            "{MANIFEST}: `{HEADER}` is not the render of plugins.yaml; run `cargo xtask fleet sync`"
        )
    })
}
