// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/bedrock.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Cond, Field, Slot, Table, row};

/// Row group `inference_config`.
pub(crate) const ROWS_INFERENCE_CONFIG: &[Field] = &[
    row(&["inferenceConfig", "temperature"], Slot::Temperature, Codec::Plain).clamp(0.0, 1.0, "clamping temperature to Bedrock's [0.0, 1.0] range; the requested value was out of range and would be rejected with a 400 ValidationException", false).drop_if(Cond::Thinking, "omitting temperature on Bedrock egress: not compatible with thinking", true),
    row(&["inferenceConfig", "topP"], Slot::TopP, Codec::Plain).drop_if(Cond::Thinking, "omitting topP on Bedrock egress: not compatible with thinking", true),
    row(&["inferenceConfig", "stopSequences"], Slot::Stop, Codec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_INFERENCE_CONFIG];
