// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/openai_chat.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Dir, Field, Hook, Slot, Table, Word, row};

/// Row group `chat`.
pub(crate) const ROWS_CHAT: &[Field] = &[
    row(&["verbosity"], Slot::Verbosity, Codec::Plain),
    row(&["modalities"], Slot::OutputModalities, Codec::Hook(Hook::ChatModalities)),
    row(&["web_search_options"], Slot::WebSearch, Codec::Hook(Hook::ChatWebSearch)),
];

/// Row group `openai_family`.
pub(crate) const ROWS_OPENAI_FAMILY: &[Field] = &[
    row(&["metadata"], Slot::Metadata, Codec::Plain),
    row(&["service_tier"], Slot::ServiceTier, Codec::Plain),
    row(&["store"], Slot::Store, Codec::Plain),
    row(&["safety_identifier"], Slot::SafetyIdentifier, Codec::Plain),
    row(&["prompt_cache_key"], Slot::PromptCacheKey, Codec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_OPENAI_FAMILY, ROWS_CHAT];

/// Word table `openai_served_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_OPENAI_SERVED_TIER: &[Word] = &[
    ("default", "standard", Dir::Both),
    ("default", "default", Dir::Write),
    ("priority", "priority", Dir::Both),
    ("flex", "flex", Dir::Write),
    ("scale", "scale", Dir::Write),
];

/// Word table `served_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_SERVED_TIER: &[Word] = &[
    ("default", "standard", Dir::Both),
    ("default", "default", Dir::Write),
    ("priority", "priority", Dir::Both),
    ("flex", "flex", Dir::Write),
    ("scale", "scale", Dir::Write),
    ("flex", "flex", Dir::Read),
    ("scale", "scale", Dir::Read),
];
