// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/openai_chat.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Dir, Field, Handled, Hook, Slot, Table, Word, row};

/// Row group `chat`.
pub(crate) const ROWS_CHAT: &[Field] = &[
    row(&["verbosity"], Slot::Verbosity, Codec::Plain).park(),
    row(&["modalities"], Slot::OutputModalities, Codec::Hook(Hook::ChatModalities)).park(),
    row(&["web_search_options"], Slot::WebSearch, Codec::Hook(Hook::ChatWebSearch)).park(),
];

/// Row group `chat_sampling`.
pub(crate) const ROWS_CHAT_SAMPLING: &[Field] = &[
    row(&["stop"], Slot::Stop, Codec::Plain).cap(4, "OpenAI"),
    row(&["n"], Slot::N, Codec::Plain),
];

/// Row group `chat_structure`.
pub(crate) const ROWS_CHAT_STRUCTURE: &[Field] = &[
    row(&["model"], Slot::Structure, Codec::Prim("model")),
    row(&["messages"], Slot::Structure, Codec::Prim("messages")),
    row(&["tools"], Slot::Structure, Codec::Prim("tools")),
    row(&["max_tokens"], Slot::Structure, Codec::Prim("max_output")),
    row(&["max_completion_tokens"], Slot::Structure, Codec::Prim("max_output")),
    row(&["stream"], Slot::Structure, Codec::Prim("stream")),
    row(&["tool_choice"], Slot::Structure, Codec::Prim("tool_choice")),
    row(&["response_format"], Slot::Structure, Codec::Prim("response_format")),
    row(&["user"], Slot::Structure, Codec::Prim("user")),
    row(&["parallel_tool_calls"], Slot::Structure, Codec::Prim("parallel_tool_calls")),
    row(&["logprobs"], Slot::Structure, Codec::Prim("logprobs")),
    row(&["top_logprobs"], Slot::Structure, Codec::Prim("logprobs")),
    row(&["reasoning_effort"], Slot::Structure, Codec::Prim("reasoning")),
];

/// Row group `openai_family`.
pub(crate) const ROWS_OPENAI_FAMILY: &[Field] = &[
    row(&["metadata"], Slot::Metadata, Codec::Plain).park(),
    row(&["service_tier"], Slot::ServiceTier, Codec::Plain).park(),
    row(&["store"], Slot::Store, Codec::Plain).park(),
    row(&["safety_identifier"], Slot::SafetyIdentifier, Codec::Plain).park(),
    row(&["prompt_cache_key"], Slot::PromptCacheKey, Codec::Plain).park(),
];

/// Row group `openai_penalties`.
pub(crate) const ROWS_OPENAI_PENALTIES: &[Field] = &[
    row(&["frequency_penalty"], Slot::FrequencyPenalty, Codec::Plain),
    row(&["presence_penalty"], Slot::PresencePenalty, Codec::Plain),
    row(&["seed"], Slot::Seed, Codec::Plain),
];

/// Row group `openai_sampling`.
pub(crate) const ROWS_OPENAI_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, Codec::Plain),
    row(&["top_p"], Slot::TopP, Codec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_CHAT_STRUCTURE, ROWS_OPENAI_SAMPLING, ROWS_OPENAI_PENALTIES, ROWS_CHAT_SAMPLING, ROWS_OPENAI_FAMILY, ROWS_CHAT];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::TopK, Handled::Silent),
    (Slot::CustomTool, Handled::Code("chat_custom_tools")),
];

/// Word table `openai_served_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_OPENAI_SERVED_TIER: &[Word] = &[
    ("default", "standard", Dir::Both),
    ("default", "default", Dir::Write),
    ("priority", "priority", Dir::Both),
    ("flex", "flex", Dir::Write),
    ("scale", "scale", Dir::Write),
];

/// Word table `served_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_SERVED_TIER: &[Word] = &[
    ("default", "standard", Dir::Both),
    ("default", "default", Dir::Write),
    ("priority", "priority", Dir::Both),
    ("flex", "flex", Dir::Write),
    ("scale", "scale", Dir::Write),
    ("flex", "flex", Dir::Read),
    ("scale", "scale", Dir::Read),
];
