// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE FIELD COVERAGE GATE. Every request and response field of every chat dialect busbar speaks
//! is either `carried` (with a named test that fails if it stops being carried), `waived` (with a
//! dated reason), or **MISSING — and the MISSING set is pinned, so it fails the build the moment it
//! changes in either direction.**
//!
//! Owner's ruling, 2026-08-13, and it is the whole reason this file exists:
//!
//! > *"good fix it all. IR completion is key. we say we dont leave things on floor, its our
//! > differentiator. needs to be solid"*
//!
//! ## Why a gate and not a fixed list of defects
//!
//! The 1.6.0 IR-losslessness audit ranked six losses. Its most important finding was not any of
//! them — it was the reason they went unnoticed: **the exposure lived in fields that are never read
//! and never emitted.** A mutation pass renamed eight writer-emitted keys and all eight were caught
//! by name; meanwhile audio attachments, usage sub-buckets and citation offsets were being dropped
//! in silence, because **you cannot mutate a field that does not exist.**
//!
//! So a list of six is a list of six things somebody happened to notice. This gate makes the CLASS
//! enumerable, exactly as [`method_coverage`](../method_coverage.rs) does for MCP/A2A methods, and
//! for the reason `scripts/method-inventory.py` states: a hand-written list is how coverage ends at
//! J with nobody noticing, because an absent row and a considered-and-inapplicable row look
//! identical on the page.
//!
//! ## The three inputs, none of which is prose
//!
//! | file | what it is | who writes it |
//! |---|---|---|
//! | `qa/field-inventory.json` | every field of every dialect | GENERATED by `scripts/field-inventory.py` from the vendored schemas in `qa/field-schemas/` |
//! | `qa/field-coverage.status` | the `carried` / `waived` claims | a human, one line per field, a TEST NAME on every `carried` and a dated reason on every waiver |
//! | `qa/field-coverage.missing` | the pinned MISSING set | a human, deliberately, by reading a diff |
//!
//! ## `carried` means an instrument watched it
//!
//! A `carried` line names a test function, and [`every_carried_claim_names_a_real_test`] fails if
//! that function does not exist in the tree. **A field a test would not miss is a field the next
//! edit drops silently** — which is precisely how the audited six arrived. This is the same bar the
//! method matrix holds: a cell counts only if an instrument was watched saying so.
//!
//! ## Why it is RED today, and why that is the deliverable
//!
//! Most of the 412 enumerated fields are not yet backed by an instrument. Claiming them on the
//! strength of "the reader looks like it handles that" would be claiming coverage the release does
//! not have — the exact move this gate exists to make impossible. So the unbacked fields are
//! MISSING, `qa/field-coverage.missing` pins every one of them, and the pin is the 1.6.x work
//! queue: it is not possible to land a field without editing that file.
//!
//! The repo's own convention for a deliberately-red gate is the one
//! `testing/a2a-tck/check-baseline.py` states: *"a suite whose result is UNCHANGING is still a
//! gate, because the thing a gate has to catch is a CHANGE."*
//!
//! **Never weaken this gate to make it green.** Do not move a line from `.missing` to a waiver to
//! make a number look better: a waiver says "not owed, and here is why", and laundering a gap into
//! one is how the losslessness claim became false in the first place.

use std::collections::{BTreeMap, BTreeSet};

fn repo_root() -> std::path::PathBuf {
    // CARGO_MANIFEST_DIR is crates/busbar; the repo root is two levels up.
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root")
        .to_path_buf()
}

fn read(rel: &str) -> String {
    let p = repo_root().join(rel);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("cannot read {}: {e}", p.display()))
}

/// Every field id in the generated inventory, in the file's own order.
fn inventory_ids() -> Vec<String> {
    let doc: serde_json::Value = serde_json::from_str(&read("qa/field-inventory.json"))
        .expect("field-inventory.json parses");
    let fields = doc["fields"].as_array().expect("fields array");
    assert!(
        !fields.is_empty(),
        "the inventory is EMPTY — a gate over nothing is not a gate. Run \
         scripts/field-inventory.py --write"
    );
    fields
        .iter()
        .map(|f| {
            f["id"]
                .as_str()
                .expect("every field carries a string id")
                .to_string()
        })
        .collect()
}

/// One declared status: `carried <test_fn>` or `waived <date> <reason>`.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Status {
    Carried { test: String },
    Waived { date: String, reason: String },
}

fn parse_status() -> BTreeMap<String, Status> {
    let mut out = BTreeMap::new();
    for (lineno, raw) in read("qa/field-coverage.status").lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // `rsplit_once(" = ")`, not `split_once('=')`: a field id legitimately CONTAINS an `=`
        // (a discriminated content part is spelled `content[].type=input_audio.…`), so splitting on
        // the first bare `=` truncates the id and silently mismatches every such field against the
        // inventory. The separator is the spaced ` = `, and the LAST one wins.
        let (id, rest) = line.rsplit_once(" = ").unwrap_or_else(|| {
            panic!(
                "qa/field-coverage.status:{}: no ` = ` separator in {line:?}",
                lineno + 1
            )
        });
        let id = id.trim().to_string();
        assert!(
            !id.contains('*') && !id.contains('?'),
            "qa/field-coverage.status:{}: wildcards are forbidden — a glob waiver is how a whole \
             surface disappears in one line",
            lineno + 1
        );
        let rest = rest.trim();
        let status = if let Some(test) = rest.strip_prefix("carried ") {
            let test = test.trim();
            assert!(
                !test.is_empty(),
                "qa/field-coverage.status:{}: `carried` must name the test that proves it",
                lineno + 1
            );
            Status::Carried {
                test: test.to_string(),
            }
        } else if let Some(w) = rest.strip_prefix("waived ") {
            let (date, reason) = w.trim().split_once(' ').unwrap_or_else(|| {
                panic!(
                    "qa/field-coverage.status:{}: `waived` needs a date AND a reason",
                    lineno + 1
                )
            });
            assert!(
                date.len() == 10 && date.chars().filter(|c| *c == '-').count() == 2,
                "qa/field-coverage.status:{}: waiver date must be YYYY-MM-DD, got {date:?}",
                lineno + 1
            );
            assert!(
                reason.trim().len() >= 20,
                "qa/field-coverage.status:{}: a waiver reason must be something a customer could \
                 read, got {reason:?}",
                lineno + 1
            );
            Status::Waived {
                date: date.to_string(),
                reason: reason.trim().to_string(),
            }
        } else {
            panic!(
                "qa/field-coverage.status:{}: state must be `carried <test>` or \
                 `waived <YYYY-MM-DD> <reason>`, got {rest:?}",
                lineno + 1
            );
        };
        assert!(
            out.insert(id.clone(), status).is_none(),
            "qa/field-coverage.status: duplicate entry for {id}"
        );
    }
    out
}

fn parse_missing() -> BTreeSet<String> {
    read("qa/field-coverage.missing")
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(String::from)
        .collect()
}

/// Every id named in the status file must exist in the generated inventory.
///
/// The failure this catches is a claim that outlives its field: a dialect renames something, the
/// inventory follows, and a stale `carried` line goes on asserting coverage of a field nobody can
/// send any more — which inflates the covered count with a fiction.
#[test]
fn every_status_line_names_a_real_field() {
    let inv: BTreeSet<String> = inventory_ids().into_iter().collect();
    let status = parse_status();
    let unknown: Vec<&String> = status.keys().filter(|k| !inv.contains(*k)).collect();
    assert!(
        unknown.is_empty(),
        "qa/field-coverage.status names field(s) that are not in qa/field-inventory.json. Either \
         the schema moved (regenerate with scripts/field-inventory.py --write) or the line is \
         stale:\n{unknown:#?}"
    );
}

/// Every `carried` claim must name a test function that EXISTS.
///
/// This is the load-bearing assertion of the whole gate. "The IR has a member for it" is not
/// coverage — the audited losses were all in fields nothing read and nothing emitted, where a
/// mutation test had nothing to break. A claim of survival is admissible only with an instrument
/// attached, so the named function is looked for in the tree and its absence is a build failure.
#[test]
fn every_carried_claim_names_a_real_test() {
    let status = parse_status();
    let mut wanted: BTreeSet<&str> = BTreeSet::new();
    for s in status.values() {
        if let Status::Carried { test } = s {
            wanted.insert(test.as_str());
        }
    }
    // Scan the engine's sources once; a test function is `fn <name>(`. BOTH roots since the core
    // split (step 3.7): the instruments live in busbar-core, and a scanner that read only the thin
    // bin would call every claim a ghost — or, pointed the other way, would go green over nothing.
    let mut haystack = String::new();
    let mut stack = vec![
        repo_root().join("crates/busbar-core/src"),
        repo_root().join("crates/busbar/src"),
    ];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().and_then(|x| x.to_str()) == Some("rs") {
                if let Ok(t) = std::fs::read_to_string(&p) {
                    haystack.push_str(&t);
                    haystack.push('\n');
                }
            }
        }
    }
    let ghosts: Vec<&&str> = wanted
        .iter()
        .filter(|t| !haystack.contains(&format!("fn {t}(")))
        .collect();
    assert!(
        ghosts.is_empty(),
        "qa/field-coverage.status claims field(s) are `carried` by test(s) that DO NOT EXIST. A \
         field whose instrument is imaginary is a field nothing would notice being dropped:\n\
         {ghosts:#?}"
    );
}

/// The pinned MISSING set must EXACTLY equal the computed one, in both directions.
///
/// * a field that appears in `.missing` and is now `carried`/`waived` → red. Delete the line in the
///   same commit that lands the coverage, so the work queue shrinks visibly.
/// * a field that regresses into MISSING → red, because it is not listed there.
#[test]
fn pinned_missing_set_is_exact() {
    let status = parse_status();
    let computed: BTreeSet<String> = inventory_ids()
        .into_iter()
        .filter(|id| !status.contains_key(id))
        .collect();
    let pinned = parse_missing();

    let newly_missing: Vec<&String> = computed.difference(&pinned).collect();
    let no_longer_missing: Vec<&String> = pinned.difference(&computed).collect();

    assert!(
        newly_missing.is_empty(),
        "field(s) are MISSING that qa/field-coverage.missing does not pin. Either classify them in \
         qa/field-coverage.status (with a test, or a dated waiver reason) or add them to the \
         pinned queue — never leave a field unclassified, because an unclassified field is exactly \
         a field nobody is watching:\n{newly_missing:#?}"
    );
    assert!(
        no_longer_missing.is_empty(),
        "field(s) pinned as MISSING are now classified — GOOD. Delete these lines from \
         qa/field-coverage.missing in the same commit, so the work queue shrinks \
         visibly:\n{no_longer_missing:#?}"
    );
}

/// FULL-STRENGTH ACCEPTANCE: every enumerated field is carried or waived, and nothing is MISSING.
///
/// Kept at full strength and `#[ignore]`d rather than weakened, exactly as
/// `method_coverage::every_cell_is_implemented_or_waived` is. Run it with `-- --ignored`. It is red
/// today by design: the field work queue is `qa/field-coverage.missing` and it is long, because
/// claiming a field without an instrument is the move that made "lossless" false.
#[test]
#[ignore = "1.6.x acceptance: the field work queue in qa/field-coverage.missing is the deliverable, \
            and a visible red queue is the honest shape of a partial sweep"]
fn every_field_is_carried_or_waived() {
    let status = parse_status();
    let missing: Vec<String> = inventory_ids()
        .into_iter()
        .filter(|id| !status.contains_key(id))
        .collect();
    assert!(
        missing.is_empty(),
        "{} field(s) are neither carried nor waived:\n{missing:#?}",
        missing.len()
    );
}
