// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE FIELD COVERAGE GATE. Every request and response field of every chat dialect busbar speaks
//! is either `carried` (with a named test that fails if it stops being carried), `waived` (with a
//! dated reason), or **MISSING — and the MISSING set is pinned, so it fails the build the moment it
//! changes in either direction.**
//!
//! Owner's ruling, 2026-08-13, and it is the whole reason this file exists:
//!
//! > *"good fix it all. IR completion is key. we say we dont leave things on floor, its our
//! > differentiator. needs to be solid"*
//!
//! ## Why a gate and not a fixed list of defects
//!
//! The 1.6.0 IR-losslessness audit ranked six losses. Its most important finding was not any of
//! them — it was the reason they went unnoticed: **the exposure lived in fields that are never read
//! and never emitted.** A mutation pass renamed eight writer-emitted keys and all eight were caught
//! by name; meanwhile audio attachments, usage sub-buckets and citation offsets were being dropped
//! in silence, because **you cannot mutate a field that does not exist.**
//!
//! So a list of six is a list of six things somebody happened to notice. This gate makes the CLASS
//! enumerable, exactly as [`method_coverage`](../method_coverage.rs) does for MCP/A2A methods, and
//! for the reason `scripts/method-inventory.py` states: a hand-written list is how coverage ends at
//! J with nobody noticing, because an absent row and a considered-and-inapplicable row look
//! identical on the page.
//!
//! ## The three inputs, none of which is prose
//!
//! | file | what it is | who writes it |
//! |---|---|---|
//! | `qa/field-inventory.json` | every field of every dialect | GENERATED by `cargo xtask gate field-inventory --write` from the vendored schemas in `qa/field-schemas/` |
//! | `qa/field-coverage.status` | the `carried` / `waived` claims | a human, one line per field, a TEST NAME on every `carried` and a dated reason on every waiver |
//! | `qa/field-coverage.missing` | the pinned MISSING set | a human, deliberately, by reading a diff |
//!
//! ## `carried` means an instrument watched it
//!
//! A `carried` line names a test function, and [`every_carried_claim_names_a_real_test`] fails if
//! that function does not exist in the tree. **A field a test would not miss is a field the next
//! edit drops silently** — which is precisely how the audited six arrived. This is the same bar the
//! method matrix holds: a cell counts only if an instrument was watched saying so.
//!
//! ## Why it is RED today, and why that is the deliverable
//!
//! Most of the 412 enumerated fields are not yet backed by an instrument. Claiming them on the
//! strength of "the reader looks like it handles that" would be claiming coverage the release does
//! not have — the exact move this gate exists to make impossible. So the unbacked fields are
//! MISSING, `qa/field-coverage.missing` pins every one of them, and the pin is the 1.6.x work
//! queue: it is not possible to land a field without editing that file.
//!
//! The repo's own convention for a deliberately-red gate is the one
//! `testing/a2a-tck/check-baseline.py` states: *"a suite whose result is UNCHANGING is still a
//! gate, because the thing a gate has to catch is a CHANGE."*
//!
//! **Never weaken this gate to make it green.** Do not move a line from `.missing` to a waiver to
//! make a number look better: a waiver says "not owed, and here is why", and laundering a gap into
//! one is how the losslessness claim became false in the first place.

mod common;

use std::collections::{BTreeMap, BTreeSet};

fn repo_root() -> std::path::PathBuf {
    // CARGO_MANIFEST_DIR is crates/busbar; the repo root is two levels up.
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root")
        .to_path_buf()
}

fn read(rel: &str) -> String {
    let p = repo_root().join(rel);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("cannot read {}: {e}", p.display()))
}

/// Every field id in the generated inventory, in the file's own order.
fn inventory_ids() -> Vec<String> {
    let doc: serde_json::Value = serde_json::from_str(&read("qa/field-inventory.json"))
        .expect("field-inventory.json parses");
    let fields = doc["fields"].as_array().expect("fields array");
    assert!(
        !fields.is_empty(),
        "the inventory is EMPTY — a gate over nothing is not a gate. Run \
         cargo xtask gate field-inventory --write"
    );
    fields
        .iter()
        .map(|f| {
            f["id"]
                .as_str()
                .expect("every field carries a string id")
                .to_string()
        })
        .collect()
}

/// One declared status: `carried <test_fn>` or `waived <date> <reason>`.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Status {
    Carried { test: String },
    Waived { date: String, reason: String },
}

fn parse_status() -> BTreeMap<String, Status> {
    let mut out = BTreeMap::new();
    for (lineno, raw) in read("qa/field-coverage.status").lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // `rsplit_once(" = ")`, not `split_once('=')`: a field id legitimately CONTAINS an `=`
        // (a discriminated content part is spelled `content[].type=input_audio.…`), so splitting on
        // the first bare `=` truncates the id and silently mismatches every such field against the
        // inventory. The separator is the spaced ` = `, and the LAST one wins.
        let (id, rest) = line.rsplit_once(" = ").unwrap_or_else(|| {
            panic!(
                "qa/field-coverage.status:{}: no ` = ` separator in {line:?}",
                lineno + 1
            )
        });
        let id = id.trim().to_string();
        assert!(
            !id.contains('*') && !id.contains('?'),
            "qa/field-coverage.status:{}: wildcards are forbidden — a glob waiver is how a whole \
             surface disappears in one line",
            lineno + 1
        );
        let rest = rest.trim();
        let status = if let Some(test) = rest.strip_prefix("carried ") {
            let test = test.trim();
            assert!(
                !test.is_empty(),
                "qa/field-coverage.status:{}: `carried` must name the test that proves it",
                lineno + 1
            );
            Status::Carried {
                test: test.to_string(),
            }
        } else if let Some(w) = rest.strip_prefix("waived ") {
            let (date, reason) = w.trim().split_once(' ').unwrap_or_else(|| {
                panic!(
                    "qa/field-coverage.status:{}: `waived` needs a date AND a reason",
                    lineno + 1
                )
            });
            assert!(
                date.len() == 10 && date.chars().filter(|c| *c == '-').count() == 2,
                "qa/field-coverage.status:{}: waiver date must be YYYY-MM-DD, got {date:?}",
                lineno + 1
            );
            assert!(
                reason.trim().len() >= 20,
                "qa/field-coverage.status:{}: a waiver reason must be something a customer could \
                 read, got {reason:?}",
                lineno + 1
            );
            Status::Waived {
                date: date.to_string(),
                reason: reason.trim().to_string(),
            }
        } else {
            panic!(
                "qa/field-coverage.status:{}: state must be `carried <test>` or \
                 `waived <YYYY-MM-DD> <reason>`, got {rest:?}",
                lineno + 1
            );
        };
        assert!(
            out.insert(id.clone(), status).is_none(),
            "qa/field-coverage.status: duplicate entry for {id}"
        );
    }
    out
}

fn parse_missing() -> BTreeSet<String> {
    read("qa/field-coverage.missing")
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(String::from)
        .collect()
}

/// Every id named in the status file must exist in the generated inventory.
///
/// The failure this catches is a claim that outlives its field: a dialect renames something, the
/// inventory follows, and a stale `carried` line goes on asserting coverage of a field nobody can
/// send any more — which inflates the covered count with a fiction.
#[test]
fn every_status_line_names_a_real_field() {
    let inv: BTreeSet<String> = inventory_ids().into_iter().collect();
    let status = parse_status();
    let unknown: Vec<&String> = status.keys().filter(|k| !inv.contains(*k)).collect();
    assert!(
        unknown.is_empty(),
        "qa/field-coverage.status names field(s) that are not in qa/field-inventory.json. Either \
         the schema moved (regenerate with cargo xtask gate field-inventory --write) or the line \
         is stale:\n{unknown:#?}"
    );
}

/// The source roots a `carried` instrument may live in.
///
/// The engine's thin bin, plus the extracted protocol crates: a dialect's instruments move out with
/// its codec, and a claim carried by a moved test is still carried. The LLM protocol is TWO crates —
/// the engine kept `busbar-llm` and the six dialect codecs (with the great majority of these
/// instruments) moved to `busbar-llm-codec` — and the SAME split was repeated for MCP, A2A and
/// voice, so each of those protocols is two roots here for the same reason: an instrument that
/// travelled with its codec is still an instrument, and a scanner that read only the half left
/// behind would call it a ghost.
///
/// Every root must EXIST ([`every_evidence_root_exists`]). `crates/busbar-core/src` sat in this list
/// for as long as the crate had been gone (item 262): a root that is not there reads as "nothing to
/// find" and never as a failure, which is how a stale path hides a shrinking search.
const EVIDENCE_ROOTS: &[&str] = &[
    "crates/busbar/src",
    "crates/busbar-llm/src",
    "crates/busbar-llm-codec/src",
    "crates/busbar-mcp/src/codec",
    "crates/busbar-plane-mcp/src",
    "crates/busbar-plane-a2a/src",
    "crates/busbar-voice-codec/src",
];

/// Every `.rs` under the evidence roots, classified once.
fn evidence_files() -> Vec<Vec<common::Line>> {
    let mut out = Vec::new();
    let mut stack: Vec<std::path::PathBuf> =
        EVIDENCE_ROOTS.iter().map(|r| repo_root().join(r)).collect();
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().and_then(|x| x.to_str()) == Some("rs") {
                if let Ok(t) = std::fs::read_to_string(&p) {
                    out.push(common::classify(&t, common::is_test_path(&p)));
                }
            }
        }
    }
    out
}

#[test]
fn every_evidence_root_exists() {
    let absent: Vec<&&str> = EVIDENCE_ROOTS
        .iter()
        .filter(|r| !repo_root().join(r).is_dir())
        .collect();
    assert!(
        absent.is_empty(),
        "evidence root(s) {absent:?} do not exist. A root that is not there is searched as empty \
         and never fails, so the search shrinks in silence — fix or drop the path."
    );
}

/// Every `carried` claim must name a test function that is REAL EVIDENCE.
///
/// This is the load-bearing assertion of the whole gate. "The IR has a member for it" is not
/// coverage — the audited losses were all in fields nothing read and nothing emitted, where a
/// mutation test had nothing to break. A claim of survival is admissible only with an instrument
/// attached, so the named function must be, somewhere under [`EVIDENCE_ROOTS`], (1) test code,
/// (2) a test the harness runs, and (3) a body that asserts — the same three checks
/// `capability_equality.rs` holds its proven cells to, from the one copy in `common`. It used to be
/// satisfied by the text `fn NAME(` anywhere, which a production helper, a doc comment and an empty
/// body all carry (item 262).
#[test]
fn every_carried_claim_names_a_real_test() {
    let status = parse_status();
    let mut wanted: BTreeSet<&str> = BTreeSet::new();
    for s in status.values() {
        if let Status::Carried { test } = s {
            wanted.insert(test.as_str());
        }
    }
    let files = evidence_files();
    let ghosts: Vec<(&str, common::NotEvidence)> = wanted
        .iter()
        .filter_map(|t| {
            common::test_fn_is_evidence(&files, t)
                .err()
                .map(|why| (*t, why))
        })
        .collect();
    assert!(
        ghosts.is_empty(),
        "qa/field-coverage.status claims field(s) are `carried` by test(s) that are NOT EVIDENCE — \
         absent, production code, not a test the harness runs, or a body that asserts nothing. A \
         field whose instrument is imaginary is a field nothing would notice being dropped:\n\
         {ghosts:#?}"
    );
}

/// THE EVIDENCE CHECK FIRES on each thing it must refuse, and accepts the one shape it must accept.
#[test]
fn the_evidence_check_refuses_a_helper_a_comment_an_empty_test_and_production_code() {
    use common::NotEvidence;
    let file = |src: &str| vec![common::classify(src, false)];
    let real = "#[cfg(test)]\nmod tests {\n    #[test]\n    fn named() {\n        assert_eq!(1, 1);\n    }\n}\n";
    assert_eq!(common::test_fn_is_evidence(&file(real), "named"), Ok(()));
    let two_hops = "#[cfg(test)]\nmod tests {\n    fn outer() {\n        inner();\n    }\n    fn inner() {\n        assert!(true);\n    }\n    #[test]\n    fn named() {\n        outer();\n    }\n}\n";
    assert_eq!(
        common::test_fn_is_evidence(&file(two_hops), "named"),
        Ok(()),
        "a test that asserts through same-file helpers two deep is a test that asserts"
    );
    for (src, want) in [
        ("// fn named() { assert!(true) }\n", NotEvidence::Absent),
        ("fn named() {\n    assert!(true);\n}\n", NotEvidence::Production),
        (
            "#[cfg(test)]\nmod tests {\n    fn named() {\n        assert!(true);\n    }\n}\n",
            NotEvidence::NotATest,
        ),
        (
            "#[cfg(test)]\nmod tests {\n    #[test]\n    fn named() {}\n}\n",
            NotEvidence::AssertsNothing,
        ),
        (
            "#[cfg(test)]\nmod tests {\n    #[test]\n    fn not_named() {\n        assert!(true);\n    }\n}\n",
            NotEvidence::Absent,
        ),
    ] {
        assert_eq!(
            common::test_fn_is_evidence(&file(src), "named"),
            Err(want),
            "{src}"
        );
    }
}

/// The pinned MISSING set must EXACTLY equal the computed one, in both directions.
///
/// * a field that appears in `.missing` and is now `carried`/`waived` → red. Delete the line in the
///   same commit that lands the coverage, so the work queue shrinks visibly.
/// * a field that regresses into MISSING → red, because it is not listed there.
#[test]
fn pinned_missing_set_is_exact() {
    let status = parse_status();
    let computed: BTreeSet<String> = inventory_ids()
        .into_iter()
        .filter(|id| !status.contains_key(id))
        .collect();
    let pinned = parse_missing();

    let newly_missing: Vec<&String> = computed.difference(&pinned).collect();
    let no_longer_missing: Vec<&String> = pinned.difference(&computed).collect();

    assert!(
        newly_missing.is_empty(),
        "field(s) are MISSING that qa/field-coverage.missing does not pin. Either classify them in \
         qa/field-coverage.status (with a test, or a dated waiver reason) or add them to the \
         pinned queue — never leave a field unclassified, because an unclassified field is exactly \
         a field nobody is watching:\n{newly_missing:#?}"
    );
    assert!(
        no_longer_missing.is_empty(),
        "field(s) pinned as MISSING are now classified — GOOD. Delete these lines from \
         qa/field-coverage.missing in the same commit, so the work queue shrinks \
         visibly:\n{no_longer_missing:#?}"
    );
}

/// FULL-STRENGTH ACCEPTANCE: every enumerated field is carried or waived, and nothing is MISSING.
///
/// Kept at full strength and `#[ignore]`d rather than weakened, exactly as
/// `method_coverage::every_cell_is_implemented_or_waived` is. Run it with `-- --ignored`. It is red
/// today by design: the field work queue is `qa/field-coverage.missing` and it is long, because
/// claiming a field without an instrument is the move that made "lossless" false.
#[test]
#[ignore = "1.6.x acceptance: the field work queue in qa/field-coverage.missing is the deliverable, \
            and a visible red queue is the honest shape of a partial sweep"]
fn every_field_is_carried_or_waived() {
    let status = parse_status();
    let missing: Vec<String> = inventory_ids()
        .into_iter()
        .filter(|id| !status.contains_key(id))
        .collect();
    assert!(
        missing.is_empty(),
        "{} field(s) are neither carried nor waived:\n{missing:#?}",
        missing.len()
    );
}
