// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE COVERAGE GATE. Every cell of `method x direction x transport`, for MCP and A2A, is either
//! `implemented`, `waived(reason, date)`, or **MISSING — and MISSING fails the build**.
//!
//! Owner's ruling, 2026-08-12, and it is the whole reason this file exists:
//!
//! > *"i want a customer to be able to do anything mcp says it can do and anything a2a says it
//! > can do. so if thats calling 20 methods we need to support it. how internally though doesnt
//! > matter. i want full alphabet coverage not just A-J. I want A-Z"*
//!
//! ## Why a test and not a document
//!
//! A document that says "these are the methods" is a claim. It is written from knowledge of the
//! specification, which is exactly how a list ends at J with nobody noticing — the author writes
//! down what they were thinking about, and what they were not thinking about is simply absent.
//! An absent row and a considered-and-inapplicable row look identical on the page.
//!
//! So the three inputs are all files, and none of them is prose:
//!
//! | file | what it is | who writes it |
//! |---|---|---|
//! | `qa/method-inventory.json` | the matrix | GENERATED by `scripts/method-inventory.py` out of rmcp 3.1.2's `model.rs` and a2a-pb 0.2.0's vendored `a2a.proto` |
//! | `qa/method-coverage.status` | the `implemented` / `waived` claims | a human, one line per cell, dated reasons on waivers |
//! | `qa/method-coverage.missing` | the pinned MISSING set | a human, deliberately, by reading a diff |
//!
//! ## Coverage is a MATRIX, not a list
//!
//! A method implemented in one direction is still a missing letter. Two axes beyond the method:
//!
//! - **direction** — busbar as **server** (it is asked) and busbar as **client** (it asks).
//!   busbar is BOTH on BOTH protocols; that is the architectural point, not an aspiration. Each
//!   cell carries the `obligation` the combination implies: `handle` when the peer originates,
//!   `issue` when busbar does.
//! - **transport** — MCP: streamable-HTTP, stdio. A2A: JSON-RPC, HTTP+JSON, gRPC.
//!
//! An N/A cell (`na_reason` in the inventory) is not owed an implementation, and the reason is
//! asserted non-empty below. **An unexplained absent cell is the failure mode this whole gate
//! exists to prevent**, so there is no way to express one.
//!
//! ## Why it is RED today, and why that is the deliverable
//!
//! `crates/busbar/src/mcp/` and `crates/busbar/src/a2a/` are deleted whole in step 15 of the
//! 1.6.0 sequence and rebuilt cell by cell. Claiming a cell on the strength of code scheduled for
//! deletion would be claiming coverage the release does not have. So every cell is MISSING and
//! `qa/method-coverage.missing` pins all of them.
//!
//! The repo's own convention for a deliberately-red gate is the one
//! `testing/a2a-tck/check-baseline.py` states: *"a suite whose result is UNCHANGING is still a
//! gate, because the thing a gate has to catch is a CHANGE."* So the red is pinned rather than
//! ignored, and [`pinned_missing_set_is_exact`] runs on every `cargo test` and fails in BOTH
//! directions — a regression into MISSING is red, and so is an implemented cell whose line was
//! not deleted from the queue. The full-strength 1.6.0 acceptance assertion,
//! [`every_cell_is_implemented_or_waived`], is kept at full strength and marked `#[ignore]` with
//! its reason; CI runs it with `-- --ignored` and it is acceptance test 5 of the release.
//!
//! **Never weaken this gate to make it green.** The MISSING list is the work queue.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// Floors. A gate that discovers nothing passes everything. These are sized well below today's
/// real numbers (230 cells, 38 MCP rows, 13 A2A rows) so an ordinary addition does not trip them,
/// and well above zero so a parser that silently reads nothing cannot report success.
const MIN_CELLS: usize = 200;
const MIN_MCP_METHODS: usize = 30;
const MIN_A2A_METHODS: usize = 11;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the repository root must exist")
}

fn read(rel: &str) -> String {
    let p = repo_root().join(rel);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("cannot read {}: {e}", p.display()))
}

#[derive(Debug, Clone)]
struct Cell {
    id: String,
    protocol: String,
    method: String,
    role: String,
    transport: String,
    obligation: String,
    na_reason: Option<String>,
}

fn inventory() -> (serde_json::Value, Vec<Cell>) {
    let doc: serde_json::Value = serde_json::from_str(&read("qa/method-inventory.json"))
        .expect("method-inventory.json parses");
    let cells = doc["cells"]
        .as_array()
        .expect("method-inventory.json has a `cells` array")
        .iter()
        .map(|c| Cell {
            id: c["id"].as_str().expect("cell id").to_string(),
            protocol: c["protocol"].as_str().expect("cell protocol").to_string(),
            method: c["method"].as_str().expect("cell method").to_string(),
            role: c["role"].as_str().expect("cell role").to_string(),
            transport: c["transport"].as_str().expect("cell transport").to_string(),
            obligation: c["obligation"]
                .as_str()
                .expect("cell obligation")
                .to_string(),
            na_reason: c["na_reason"].as_str().map(str::to_string),
        })
        .collect();
    (doc, cells)
}

/// What a line in `qa/method-coverage.status` claims.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Claim {
    Implemented,
    Waived { date: String, reason: String },
}

/// Parse the status file. Kept separate from the file read so
/// [`status_parser_refuses_the_three_ways_a_waiver_lies`] can drive it with synthetic input —
/// the waiver path is proven to work WITHOUT landing a fake waiver in the tree to prove it.
fn parse_status(src: &str) -> Result<BTreeMap<String, Claim>, String> {
    let mut out = BTreeMap::new();
    for (n, raw) in src.lines().enumerate() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let (id, rest) = line.split_once('=').ok_or_else(|| {
            format!(
                "line {}: expected `<cell-id> = <state>`, got {raw:?}",
                n + 1
            )
        })?;
        let id = id.trim();
        let rest = rest.trim();
        if id.contains('*') || id.contains('?') {
            return Err(format!(
                "line {}: `{id}` contains a wildcard. EXACT cell ids only — a glob waiver is how a \
                 whole transport disappears in one line.",
                n + 1
            ));
        }
        let claim = if rest == "implemented" {
            Claim::Implemented
        } else if let Some(tail) = rest.strip_prefix("waived") {
            let tail = tail.trim();
            let (date, reason) = tail.split_once(char::is_whitespace).unwrap_or((tail, ""));
            let date_ok = date.len() == 10
                && date.as_bytes()[4] == b'-'
                && date.as_bytes()[7] == b'-'
                && date.bytes().filter(u8::is_ascii_digit).count() == 8;
            if !date_ok {
                return Err(format!(
                    "line {}: a waiver must name the date it was taken, as YYYY-MM-DD. Got {date:?}",
                    n + 1
                ));
            }
            if reason.trim().is_empty() {
                return Err(format!(
                    "line {}: a waiver without a reason is a deletion with extra steps. Say what a \
                     customer loses and why that is acceptable.",
                    n + 1
                ));
            }
            Claim::Waived {
                date: date.to_string(),
                reason: reason.trim().to_string(),
            }
        } else {
            return Err(format!(
                "line {}: unknown state {rest:?}. A cell is `implemented`, `waived <YYYY-MM-DD> \
                 <reason>`, or absent (MISSING).",
                n + 1
            ));
        };
        if out.insert(id.to_string(), claim).is_some() {
            return Err(format!("line {}: `{id}` is claimed twice", n + 1));
        }
    }
    Ok(out)
}

fn status() -> BTreeMap<String, Claim> {
    parse_status(&read("qa/method-coverage.status")).unwrap_or_else(|e| panic!("{e}"))
}

/// The cells owed an implementation that do not have one.
fn missing(cells: &[Cell], claims: &BTreeMap<String, Claim>) -> Vec<Cell> {
    cells
        .iter()
        .filter(|c| c.na_reason.is_none() && !claims.contains_key(&c.id))
        .cloned()
        .collect()
}

fn pinned_missing() -> BTreeSet<String> {
    read("qa/method-coverage.missing")
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim().to_string())
        .filter(|l| !l.is_empty())
        .collect()
}

// ---------------------------------------------------------------------------
// 1. The inputs are well formed, and the gate is not vacuous.
// ---------------------------------------------------------------------------

#[test]
fn the_matrix_is_a_matrix_and_not_a_list() {
    let (doc, cells) = inventory();

    assert!(
        cells.len() >= MIN_CELLS,
        "only {} cells in qa/method-inventory.json. This gate refuses to pass vacuously — a \
         derivation that reads nothing would report full coverage of nothing. Regenerate with \
         `scripts/method-inventory.py --write`.",
        cells.len()
    );

    let mcp = cells.iter().filter(|c| c.protocol == "mcp").count();
    let a2a = cells.iter().filter(|c| c.protocol == "a2a").count();
    assert!(mcp > 0 && a2a > 0, "both protocols must be in the matrix");
    assert!(
        doc["counts"]["mcp_methods"].as_u64().unwrap_or(0) >= MIN_MCP_METHODS as u64,
        "the MCP method count collapsed; rmcp's model was parsed but yielded almost nothing"
    );
    assert!(
        doc["counts"]["a2a_methods"].as_u64().unwrap_or(0) >= MIN_A2A_METHODS as u64,
        "the A2A method count collapsed; a2a.proto's service block was parsed but yielded almost \
         nothing"
    );

    // Both directions, on both protocols. "Bidirectional in both directions" is the owner's
    // phrase and this is what makes it checkable rather than asserted.
    for protocol in ["mcp", "a2a"] {
        for role in ["server", "client"] {
            assert!(
                cells
                    .iter()
                    .any(|c| c.protocol == protocol && c.role == role),
                "{protocol} has no cell with busbar in the {role} role"
            );
        }
    }

    // Every transport the specifications define is a column, and a real one.
    for (protocol, transport) in [
        ("mcp", "streamable-http"),
        ("mcp", "stdio"),
        ("a2a", "jsonrpc"),
        ("a2a", "http+json"),
        ("a2a", "grpc"),
    ] {
        assert!(
            cells
                .iter()
                .any(|c| c.protocol == protocol && c.transport == transport),
            "{protocol} has no {transport} column. Transport is a real third axis (goal D8), not a \
             deployment detail."
        );
    }

    // Every method appears in BOTH roles on every transport it supports. A method implemented in
    // one direction is still a missing letter, and the matrix must be able to say so.
    let mut seen: BTreeMap<(String, String, String), BTreeSet<String>> = BTreeMap::new();
    for c in &cells {
        seen.entry((c.protocol.clone(), c.method.clone(), c.transport.clone()))
            .or_default()
            .insert(c.role.clone());
    }
    for (key, roles) in &seen {
        assert_eq!(
            roles.len(),
            2,
            "{key:?} exists in only one direction ({roles:?}). Both roles are cells; one of them \
             being absent is precisely the silent omission this gate exists to catch."
        );
    }

    // The obligation is derived, never guessed: busbar HANDLES what the peer originates and
    // ISSUES what it originates itself.
    for c in &cells {
        assert!(
            c.obligation == "handle" || c.obligation == "issue",
            "{}: obligation must be `handle` or `issue`, got {:?}",
            c.id,
            c.obligation
        );
    }
}

#[test]
fn every_na_cell_says_why_it_is_na() {
    let (_, cells) = inventory();
    let na: Vec<&Cell> = cells.iter().filter(|c| c.na_reason.is_some()).collect();
    assert!(
        !na.is_empty(),
        "no N/A cells at all. Some cells ARE legitimately N/A (A2A push delivery has no JSON-RPC \
         or gRPC form; the well-known Agent Card is not an rpc; stdio has no session verbs). Zero \
         of them means the derivation stopped recording the distinction."
    );
    for c in na {
        let reason = c.na_reason.as_deref().unwrap_or("");
        assert!(
            reason.trim().len() >= 20,
            "{} is marked N/A with reason {reason:?}. Mark N/A WITH A REASON — an unexplained \
             absent cell is indistinguishable from an oversight, which is the failure mode.",
            c.id
        );
    }
}

#[test]
fn no_status_entry_is_stale() {
    let (_, cells) = inventory();
    let ids: BTreeSet<&str> = cells.iter().map(|c| c.id.as_str()).collect();
    let claims = status();
    let stale: Vec<&String> = claims
        .keys()
        .filter(|k| !ids.contains(k.as_str()))
        .collect();
    assert!(
        stale.is_empty(),
        "qa/method-coverage.status claims cells that are not in the inventory: {stale:#?}\n\
         A stale entry excuses nothing and hides that the method it named was renamed or removed \
         upstream. Delete it, or fix the id."
    );
}

// ---------------------------------------------------------------------------
// 2. The pinned red. Runs always. Fails in BOTH directions.
// ---------------------------------------------------------------------------

#[test]
fn pinned_missing_set_is_exact() {
    let (_, cells) = inventory();
    let claims = status();
    let computed: BTreeSet<String> = missing(&cells, &claims).into_iter().map(|c| c.id).collect();

    if std::env::var("BUSBAR_PIN_MISSING_CELLS").is_ok_and(|v| v == "1") {
        let header = read("qa/method-coverage.missing");
        let header: String = header
            .lines()
            .take_while(|l| l.starts_with('#') || l.trim().is_empty())
            .map(|l| format!("{l}\n"))
            .collect();
        let body: String = computed.iter().map(|c| format!("{c}\n")).collect();
        std::fs::write(
            repo_root().join("qa/method-coverage.missing"),
            header + &body,
        )
        .expect("rewrite the pinned MISSING set");
        return;
    }

    let pinned = pinned_missing();
    let newly_missing: Vec<&String> = computed.difference(&pinned).collect();
    let newly_covered: Vec<&String> = pinned.difference(&computed).collect();

    assert!(
        newly_missing.is_empty(),
        "cells REGRESSED into MISSING and are not in the pinned queue:\n{newly_missing:#?}\n\
         Either the inventory grew (a method the specification added — implement it or waive it \
         with a reason), or a cell that was claimed lost its claim."
    );
    assert!(
        newly_covered.is_empty(),
        "cells are now covered but still sit in the work queue:\n{newly_covered:#?}\n\
         Delete their lines from qa/method-coverage.missing in the SAME commit that covers them, \
         so the queue shrinks visibly:\n  \
         BUSBAR_PIN_MISSING_CELLS=1 cargo test -p busbar --test method_coverage"
    );
}

// ---------------------------------------------------------------------------
// 3. The full-strength 1.6.0 acceptance assertion. RED BY DESIGN, kept at full strength.
// ---------------------------------------------------------------------------

/// **Acceptance test 5 of the 1.6.0 release** (`GOAL-1.6.0-UNATTENDED.md` §1.1): *"THE COVERAGE
/// GATE IS GREEN — every cell of method × direction × transport."*
///
/// `#[ignore]`d rather than deleted, and rather than softened. It is RED today because the MCP and
/// A2A modules are being deleted and rebuilt, so 210 of 230 cells are still owed. That is the
/// correct state while the rebuild runs: the failure message below IS the release's work queue, and
/// it is printed in full rather than truncated, because a `tail` of a work queue is how the last
/// item gets lost.
///
/// The count in the `#[ignore]` reason MOVES as cells land, and it is not decoration: it is the one
/// place a reader of `cargo test` output sees the queue shrink. The A2A plane's HTTP+JSON binding
/// took the first ten off it.
///
/// Run it: `cargo test -p busbar --test method_coverage -- --ignored`
/// Remove the `#[ignore]` when it passes. Do not remove it any other way.
#[test]
#[ignore = "RED BY DESIGN until 1.6.0: as of 2026-08-12, 210 of 230 cells are MISSING because \
            crates/busbar/src/{mcp,a2a}/ are being deleted and rebuilt cell by cell. The current \
            list is pinned in qa/method-coverage.missing and is the release's work queue. Run with \
            --ignored; do not weaken this test to make it green."]
fn every_cell_is_implemented_or_waived() {
    let (_, cells) = inventory();
    let claims = status();
    let gaps = missing(&cells, &claims);

    if gaps.is_empty() {
        return;
    }

    let mut report = String::new();
    report.push_str(&format!(
        "\n{} of {} cells are MISSING — neither implemented nor waived.\n\
         Every one is a thing the specification says a customer can do and busbar cannot.\n\n",
        gaps.len(),
        cells.len()
    ));
    let mut by_protocol: BTreeMap<&str, Vec<&Cell>> = BTreeMap::new();
    for c in &gaps {
        by_protocol.entry(c.protocol.as_str()).or_default().push(c);
    }
    for (protocol, list) in by_protocol {
        report.push_str(&format!(
            "== {} ({} cells)\n",
            protocol.to_uppercase(),
            list.len()
        ));
        for c in list {
            report.push_str(&format!(
                "  {:<16} busbar-as-{:<6} must {:<6} {}\n",
                c.transport, c.role, c.obligation, c.method
            ));
        }
        report.push('\n');
    }
    report.push_str(
        "Fix by implementing the cell, or by adding a dated line with a reason to \
         qa/method-coverage.status. Do not delete rows from qa/method-inventory.json — it is \
         generated from the SDKs and will come straight back.\n",
    );
    panic!("{report}");
}

// ---------------------------------------------------------------------------
// 4. The gate's own self-test: the waiver path is proven to work without landing a fake waiver.
// ---------------------------------------------------------------------------

#[test]
fn status_parser_refuses_the_three_ways_a_waiver_lies() {
    // A glob would retire a whole transport in one line.
    assert!(
        parse_status("mcp|*|server|client|tools/call = implemented").is_err(),
        "a wildcard cell id must be refused"
    );
    // A waiver with no reason is a deletion with extra steps.
    assert!(
        parse_status("mcp|stdio|server|client|ping = waived 2026-08-12").is_err(),
        "a waiver with no reason must be refused"
    );
    // A waiver with no date cannot be aged, reviewed or expired.
    assert!(
        parse_status("mcp|stdio|server|client|ping = waived because reasons").is_err(),
        "a waiver with no date must be refused"
    );
    // And a made-up state is not a fourth state.
    assert!(
        parse_status("mcp|stdio|server|client|ping = partially").is_err(),
        "there are three states and `partially` is not one of them"
    );

    // The two legitimate claims parse, and they are what silences a cell.
    let ok = parse_status(
        "# a comment\n\
         mcp|stdio|server|client|ping = implemented\n\
         \n\
         a2a|grpc|client|client|ListTasks = waived 2026-08-12 the gRPC client leg lands in step 15\n",
    )
    .expect("well-formed claims parse");
    assert_eq!(ok.len(), 2);
    assert_eq!(ok["mcp|stdio|server|client|ping"], Claim::Implemented);
    assert!(matches!(
        &ok["a2a|grpc|client|client|ListTasks"],
        Claim::Waived { date, reason } if date == "2026-08-12" && reason.starts_with("the gRPC")
    ));

    // The gate must move in both directions or it is decorative: a cell with a claim is NOT
    // missing, and the same cell without one IS.
    let (_, cells) = inventory();
    let victim = cells
        .iter()
        .find(|c| c.na_reason.is_none())
        .expect("at least one cell is owed an implementation");
    let empty = BTreeMap::new();
    assert!(
        missing(&cells, &empty).iter().any(|c| c.id == victim.id),
        "with no claims at all, {} must count as MISSING",
        victim.id
    );
    let mut claimed = BTreeMap::new();
    claimed.insert(victim.id.clone(), Claim::Implemented);
    assert!(
        !missing(&cells, &claimed).iter().any(|c| c.id == victim.id),
        "a claimed cell must stop counting as MISSING — otherwise no amount of work could ever \
         turn this gate green and it would be ignored instead of satisfied"
    );
}
