// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/openai_responses.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Field, Slot, Table, row};

/// Row group `responses`.
pub(crate) const ROWS_RESPONSES: &[Field] = &[
    row(&["text", "verbosity"], Slot::Verbosity, Codec::Plain).park(),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[crate::codec::openai_chat::map::ROWS_OPENAI_SAMPLING, crate::codec::openai_chat::map::ROWS_OPENAI_FAMILY, ROWS_RESPONSES];
