// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/openai_responses.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Dir, Field, Handled, Slot, Table, ValueCodec, Word, row};

/// Row group `openai_family`.
pub(crate) const ROWS_OPENAI_FAMILY: &[Field] = &[
    row(&["metadata"], Slot::Metadata, ValueCodec::Plain).park(),
    row(&["service_tier"], Slot::ServiceTier, ValueCodec::Plain).park(),
    row(&["store"], Slot::Store, ValueCodec::Plain).park(),
    row(&["safety_identifier"], Slot::SafetyIdentifier, ValueCodec::Plain).park(),
    row(&["prompt_cache_key"], Slot::PromptCacheKey, ValueCodec::Plain).park(),
];

/// Row group `responses`.
pub(crate) const ROWS_RESPONSES: &[Field] = &[
    row(&["text", "verbosity"], Slot::Verbosity, ValueCodec::Plain).park(),
];

/// Row group `responses_structure`.
pub(crate) const ROWS_RESPONSES_STRUCTURE: &[Field] = &[
    row(&["model"], Slot::Structure, ValueCodec::Prim("model")),
    row(&["instructions"], Slot::Structure, ValueCodec::Prim("system")),
    row(&["input"], Slot::Structure, ValueCodec::Prim("messages")),
    row(&["tools"], Slot::Structure, ValueCodec::Prim("tools")),
    row(&["max_output_tokens"], Slot::Structure, ValueCodec::Prim("max_output")),
    row(&["top_logprobs"], Slot::Structure, ValueCodec::Prim("logprobs")),
    row(&["stream"], Slot::Structure, ValueCodec::Prim("stream")),
    row(&["tool_choice"], Slot::Structure, ValueCodec::Prim("tool_choice")),
    row(&["parallel_tool_calls"], Slot::Structure, ValueCodec::Prim("parallel_tool_calls")),
    row(&["user"], Slot::Structure, ValueCodec::Prim("user")),
];

/// Row group `sampling`.
pub(crate) const ROWS_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, ValueCodec::Plain),
    row(&["top_p"], Slot::TopP, ValueCodec::Plain),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_RESPONSES_STRUCTURE, ROWS_SAMPLING, ROWS_OPENAI_FAMILY, ROWS_RESPONSES];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::TopK, Handled::Warn("responses writer: the /v1/responses API models no `top_k` parameter; dropping top_k (lossy-by-target)", false)),
    (Slot::Stop, Handled::Warn("responses writer: the /v1/responses API models no `stop` parameter; dropping {count} stop sequence(s) (lossy-by-target)", true)),
    (Slot::FrequencyPenalty, Handled::Warn("responses writer: the /v1/responses API models no `frequency_penalty`; dropping it (lossy-by-target)", true)),
    (Slot::PresencePenalty, Handled::Warn("responses writer: the /v1/responses API models no `presence_penalty`; dropping it (lossy-by-target)", true)),
    (Slot::Seed, Handled::Warn("responses writer: the /v1/responses API models no `seed`; dropping it (lossy-by-target)", true)),
    (Slot::N, Handled::Warn("responses writer: the /v1/responses API models no `n` candidate-count; dropping it (lossy-by-target)", true)),
    (Slot::OutputModalities, Handled::Code("responses_modalities")),
    (Slot::CustomTool, Handled::Code("responses_custom_tools")),
];

/// Word table `served_tier`: (wire word, IR word, direction).
pub(crate) const WORDS_SERVED_TIER: &[Word] = &[
    ("default", "standard", Dir::Both),
    ("default", "default", Dir::Write),
    ("priority", "priority", Dir::Both),
    ("flex", "flex", Dir::Write),
    ("scale", "scale", Dir::Write),
];
