// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors
//
// THE OPERATOR CREDENTIAL'S TEST REGISTRY ROW. This plane's admin-verb battery authenticates its
// admin requests through the operator credential, which the composition root links onto the auth axis
// in the shipped binary — but a plugin names no other plugin. `[package.metadata.busbar]
// test-operator-auth = [...]` in Cargo.toml lists the linked dev-dependency auth plugin as DATA; this
// script turns it into `$OUT_DIR/test_operator_auth.rs` (`extern crate X as _;` plus a macro handing
// each listed plugin's memory-ABI door to a function), which the battery includes under `cfg(test)` and
// installs. The production library never includes the file.

use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let manifest = Path::new(&manifest_dir).join("Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = std::fs::read_to_string(&manifest).expect("read Cargo.toml");
    let auth = metadata_list(&text, "package.metadata.busbar", "test-operator-auth");
    let code = boundary_table(&auth, "for_each_operator_auth_row");
    std::fs::write(Path::new(&out_dir).join("test_operator_auth.rs"), code)
        .expect("write test_operator_auth.rs");
}

/// The string array `key = [...]` under the `[table]` header of a Cargo manifest. Deliberately not a
/// TOML parser (a build script with no dependencies): the array may span lines, entries are
/// double-quoted crate names. An absent or empty list is a build failure, never an empty table — an
/// empty table would silently install nothing and the tests would read an empty roster.
fn metadata_list(manifest: &str, table: &str, key: &str) -> Vec<String> {
    let header = format!("[{table}]");
    let mut in_table = false;
    let mut collecting = false;
    let mut body = String::new();
    for line in manifest.lines() {
        let code = line.split('#').next().unwrap_or("").trim();
        if !collecting && code.starts_with('[') {
            in_table = code == header;
            continue;
        }
        if collecting {
            body.push_str(code);
        } else if in_table {
            if let Some((k, v)) = code.split_once('=') {
                if k.trim() == key {
                    collecting = true;
                    body.push_str(v.trim());
                }
            }
        }
        if collecting && body.contains(']') {
            break;
        }
    }
    let list: Vec<String> = body
        .trim()
        .trim_start_matches('[')
        .split(']')
        .next()
        .unwrap_or("")
        .split(',')
        .map(|s| s.trim().trim_matches('"').to_string())
        .filter(|s| !s.is_empty())
        .collect();
    assert!(
        !list.is_empty(),
        "Cargo.toml: `{key}` under `{header}` is missing or empty"
    );
    list
}

/// `extern crate <ident> as _;` for every listed crate, then a `for_each_operator_auth_row!($f)`
/// macro that calls `($f)(<ident>::door::door)` for each — the plugin's memory-ABI door — in list
/// order.
fn boundary_table(crates: &[String], name: &str) -> String {
    let idents: Vec<String> = crates.iter().map(|c| c.replace('-', "_")).collect();
    let mut out = String::from("// @generated by build.rs from Cargo.toml metadata.\n");
    for id in &idents {
        out.push_str(&format!("extern crate {id} as _;\n"));
    }
    out.push_str(&format!("macro_rules! {name} {{\n    ($f:expr) => {{{{\n"));
    for id in &idents {
        out.push_str(&format!("        ($f)({id}::door::door);\n"));
    }
    out.push_str("    }};\n}\n");
    out
}
