// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/cohere.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Codec, Field, Slot, Table, row};

/// Row group `sampling`.
pub(crate) const ROWS_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, Codec::Plain).clamp(0.0, 1.0, "clamping temperature to Cohere's [0.0, 1.0] range; the requested value was outside it (e.g. an OpenAI/Responses value up to 2.0) and would 400 — the forwarded value diverges from the caller's request", true),
    row(&["p"], Slot::TopP, Codec::Plain),
    row(&["k"], Slot::TopK, Codec::Plain),
    row(&["stop_sequences"], Slot::Stop, Codec::Plain).cap(5, "Cohere"),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_SAMPLING, crate::codec::openai_chat::map::ROWS_OPENAI_PENALTIES];
