// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

// @generated by `cargo xtask dialect compile` from crates/busbar-plane-llm/dialects/cohere.toml.
// DO NOT EDIT: edit the mapping file and re-run the compile; the `dialect-map` gate refuses
// a table file that differs from a fresh compile.

use crate::codec::carry::{Field, Handled, Slot, Table, ValueCodec, row};

/// Row group `blocks`.
pub(crate) const ROWS_BLOCKS: &[Field] = &[
    row(&["messages[]", "role=tool", "content[]", "type=document", "document", "id"], Slot::Structure, ValueCodec::Prim("id")),
    row(&["messages[]", "role=tool", "content[]", "type=document", "document", "data"], Slot::Structure, ValueCodec::Prim("data")),
    row(&["messages[]", "role=tool", "tool_call_id"], Slot::Structure, ValueCodec::Prim("tool_call_id")),
    row(&["messages[]", "role=assistant", "tool_calls"], Slot::Structure, ValueCodec::Prim("tool_calls")),
    row(&["messages[]", "role=assistant"], Slot::Structure, ValueCodec::Prim("assistant")),
    row(&["messages[]", "role=tool"], Slot::Structure, ValueCodec::Prim("tool")),
    row(&["messages[]", "role=user"], Slot::Structure, ValueCodec::Prim("user")),
    row(&["messages[]", "role=tool", "content"], Slot::Structure, ValueCodec::Prim("content")),
    row(&["messages[]", "role=user", "content"], Slot::Structure, ValueCodec::Prim("content")),
    row(&["messages[]", "role=system", "content"], Slot::Structure, ValueCodec::Prim("content")),
    row(&["messages[]", "role=assistant", "content"], Slot::Structure, ValueCodec::Prim("content")),
    row(&["messages[]", "role=assistant", "tool_plan"], Slot::Structure, ValueCodec::Prim("tool_plan")),
    row(&["messages[]", "role=assistant", "citations"], Slot::Structure, ValueCodec::Prim("citations")),
    row(&["messages[]", "role=tool", "content[]", "type=text", "text"], Slot::Structure, ValueCodec::Prim("text")),
    row(&["messages[]", "role=user", "content[]", "type=text", "text"], Slot::Structure, ValueCodec::Prim("text")),
    row(&["messages[]", "role=system", "content[]", "type=text", "text"], Slot::Structure, ValueCodec::Prim("text")),
    row(&["messages[]", "role=assistant", "content[]", "type=text", "text"], Slot::Structure, ValueCodec::Prim("text")),
    row(&["messages[]", "role=user", "content[]", "type=image_url", "image_url", "url"], Slot::Structure, ValueCodec::Prim("url")),
    row(&["messages[]", "role=assistant", "content[]", "type=thinking", "thinking"], Slot::Structure, ValueCodec::Prim("thinking")),
    row(&["messages[]", "role=assistant", "tool_calls[]", "function", "name"], Slot::Structure, ValueCodec::Prim("name")),
    row(&["tools[]", "function", "name"], Slot::Structure, ValueCodec::Prim("name")),
];

/// Row group `penalties`.
pub(crate) const ROWS_PENALTIES: &[Field] = &[
    row(&["frequency_penalty"], Slot::FrequencyPenalty, ValueCodec::Plain),
    row(&["presence_penalty"], Slot::PresencePenalty, ValueCodec::Plain),
    row(&["seed"], Slot::Seed, ValueCodec::Plain),
];

/// Row group `sampling`.
pub(crate) const ROWS_SAMPLING: &[Field] = &[
    row(&["temperature"], Slot::Temperature, ValueCodec::Plain).clamp(0.0, 1.0, "clamping temperature to Cohere's [0.0, 1.0] range; the requested value was outside it (e.g. an OpenAI/Responses value up to 2.0) and would 400 — the forwarded value diverges from the caller's request", true),
    row(&["p"], Slot::TopP, ValueCodec::Plain),
    row(&["k"], Slot::TopK, ValueCodec::Plain),
    row(&["stop_sequences"], Slot::Stop, ValueCodec::Plain).cap(5, "Cohere"),
];

/// Row group `structure`.
pub(crate) const ROWS_STRUCTURE: &[Field] = &[
    row(&["model"], Slot::Structure, ValueCodec::Prim("model")),
    row(&["messages"], Slot::Structure, ValueCodec::Prim("messages")),
    row(&["messages[]", "role=system"], Slot::Structure, ValueCodec::Prim("system")),
    row(&["messages[]", "role=assistant", "tool_calls[]", "function", "arguments"], Slot::Structure, ValueCodec::Prim("tool_arguments")),
    row(&["tools"], Slot::Structure, ValueCodec::Prim("tools")),
    row(&["tool_choice"], Slot::Structure, ValueCodec::Prim("tool_choice")),
    row(&["max_tokens"], Slot::Structure, ValueCodec::Prim("max_output")),
    row(&["stream"], Slot::Structure, ValueCodec::Prim("stream")),
    row(&["response_format"], Slot::Structure, ValueCodec::Prim("response_format")),
    row(&["logprobs"], Slot::Structure, ValueCodec::Prim("logprobs")),
];

/// The request table, walked in order.
pub(crate) const REQUEST: Table = &[ROWS_STRUCTURE, ROWS_SAMPLING, ROWS_PENALTIES, ROWS_BLOCKS];

/// How each control slot beyond the rows is handled.
pub(crate) const CONTROLS: &[(Slot, Handled)] = &[
    (Slot::N, Handled::Silent),
    (Slot::CustomTool, Handled::Code("cohere_hosted_tools")),
];

/// The warn for every other derived drop.
pub(crate) const DROP_WARN: crate::codec::dialect::DropWarn =
    crate::codec::dialect::DropWarn::Control("dropping a request control on Cohere egress: Cohere v2 /chat has no form for it");
