#!/usr/bin/env bash
# Shared transport for the two remote entry points: scripts/land.sh --remote and
# scripts/prove-remote.sh. Nothing here runs a proof; it gets a shell, a host and a tree onto a box.
#
# ── WHY SSH GOES THROUGH SSM, AND WHY THE SECURITY GROUP STILL OPENS NOTHING ────────────────────
# The obvious shape — open tcp/22 to the operator's /32 and ssh to the public IP — was built, tried
# and abandoned on evidence. Outbound 22 (and 443-as-ssh) from the operator's network never reaches
# the box: the TCP handshake "succeeds" against *any* address, including 1.2.3.4, which is a
# middlebox forging SYN-ACK and then dropping the stream, so every session died in `banner exchange`
# while sshd sat healthy on the box and logged nothing. A rule that admits an operator who cannot
# connect is an attack surface bought for nothing.
#
# So the transport is `aws ssm start-session --document-name AWS-StartSSHSession` as an ssh
# ProxyCommand: the ssh stream is tunnelled inside the SSM channel, which is ordinary HTTPS to the
# regional SSM endpoint. This is strictly better than the rule it replaces:
#   * the security group stays EGRESS-ONLY — nothing on the fleet listens to the internet;
#   * there is no operator IP to keep current, and no rule to re-add when the ISP rotates it;
#   * access is IAM, so it is revoked by removing a policy rather than by editing a CIDR, and every
#     session is recorded in CloudTrail against a named principal;
#   * the host is the INSTANCE ID, stable for the life of the box, unlike a public IP.
# The cost is one local dependency, `session-manager-plugin`; ci-runners-ssh.sh installs it.
#
# THE SSH INVOCATION IS A GENERATED WRAPPER SCRIPT, not a shell variable. `ssh`, `scp` and
# `GIT_SSH_COMMAND` each want the same options, and one of those options is a ProxyCommand
# containing quoted whitespace and `%h`/`%p` tokens. Passing that through three different quoting
# regimes is how a transport acquires a bug that only shows up on the host whose name has a dash in
# it. One executable file, three consumers, no re-quoting.
set -uo pipefail

: "${AWS_REGION:=us-east-1}"
export AWS_REGION AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-$AWS_REGION}"
export PATH="$HOME/.local/bin:$PATH"   # session-manager-plugin, installed without root

FLEET_FILE="${BUSBAR_FLEET_FILE:-$HOME/.busbar-fleet}"
FLEET_KEY="${FLEET_SSH_KEY:-$HOME/.ssh/busbar-ci-fleet}"
REMOTE_USER="${BUSBAR_REMOTE_USER:-ubuntu}"
REMOTE_BARE="${BUSBAR_REMOTE_BARE:-busbar.git}"     # relative to the remote user's home
REMOTE_WORK="${BUSBAR_REMOTE_WORK:-busbar-prove}"
SSH_WRAP="${BUSBAR_SSH_WRAPPER:-$HOME/.busbar-fleet-ssh}"

rlog() { printf '[remote %s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
rdie() { printf 'ERROR: %s\n' "$*" >&2; exit 2; }

remote_wrapper() {
  cat > "$SSH_WRAP" <<WRAP
#!/bin/sh
# GENERATED by scripts/ci-remote-lib.sh. The one ssh invocation the fleet is reached by.
exec ssh -i "$FLEET_KEY" \\
  -o StrictHostKeyChecking=accept-new \\
  -o UserKnownHostsFile="$HOME/.ssh/known_hosts_busbar_fleet" \\
  -o LogLevel=ERROR \\
  -o ServerAliveInterval=30 -o ServerAliveCountMax=6 \\
  -o ControlMaster=auto -o ControlPath="$HOME/.ssh/cm-busbar-%r@%h" -o ControlPersist=10m \\
  -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p --region $AWS_REGION" \\
  "\$@"
WRAP
  chmod 0755 "$SSH_WRAP"
  command -v session-manager-plugin >/dev/null \
    || rdie "session-manager-plugin is not on PATH — run ./scripts/ci-runners-ssh.sh to install it"
}

# ── The host allocator ──────────────────────────────────────────────────────────────────────────
# The cursor is a FILE, not a shell variable, because the callers are separate processes:
# prove-remote.sh invoked from four worktrees is four `bash` invocations sharing only the filesystem.
fleet_hosts() {
  [ -f "$FLEET_FILE" ] || rdie "no $FLEET_FILE — run ./scripts/ci-runners-ssh.sh first"
  awk 'NF && $1 !~ /^#/ {print $1}' "$FLEET_FILE"
}

# READY AND LEAST LOADED, NOT BLIND ROUND-ROBIN. Measured 20:2x: the cursor handed a landing to a
# box that no longer answered (a reclaimed spot instance) and the whole queue HALTed on "push
# failed"; every box also hosts four CI runner agents, so the 1-minute load differs threefold across
# the fleet in any given minute. Each candidate, starting at the cursor, is asked with a short
# timeout whether it is prepared and what its load is; the prepared box with the lowest load wins
# and a box that does not answer is skipped, not chosen. The cursor still advances so equal loads
# spread. A named host is never second-guessed — the allocator is only consulted when nothing was named.
_fleet_tmo() { if command -v timeout >/dev/null 2>&1; then timeout "$@"; else shift; "$@"; fi; }
fleet_pick_host() {
  local hosts n cur cursor h probe best="" bestload=""
  hosts="$(fleet_hosts)"
  n="$(printf '%s\n' "$hosts" | grep -c .)"
  [ "$n" -gt 0 ] || rdie "$FLEET_FILE names no hosts"
  cursor="${FLEET_FILE}.cursor"
  cur="$(cat "$cursor" 2>/dev/null || echo 0)"
  case "$cur" in ''|*[!0-9]*) cur=0 ;; esac
  echo $(( (cur + 1) % n )) > "$cursor" 2>/dev/null || true
  for h in $(printf '%s\n' "$hosts" | awk -v s=$((cur % n)) 'NR>s'; printf '%s\n' "$hosts" | awk -v s=$((cur % n)) 'NR<=s'); do
    probe="$(_fleet_tmo 15 "$SSH_WRAP" "$REMOTE_USER@$h" 'test -d ~/busbar.git && test -d ~/busbar-prove && cut -d" " -f1 /proc/loadavg' </dev/null 2>/dev/null || true)"
    case "$probe" in ''|*[!0-9.]*) rlog "fleet: $h skipped (unreachable or unprepared)"; continue ;; esac
    if [ -z "$best" ] || awk -v a="$probe" -v b="$bestload" 'BEGIN { exit !(a + 0 < b + 0) }'; then best="$h"; bestload="$probe"; fi
  done
  [ -n "$best" ] || rdie "no prepared, reachable box among the $n in $FLEET_FILE"
  rlog "fleet: $best chosen (1-min load $bestload)"
  printf '%s\n' "$best"
}

# N DISTINCT BOXES, LEAST LOADED FIRST, NEVER ONE OF THE EXCLUDED — for the shard fan-out, which
# hands one self-test shard to each of them while the primary runs its own. One probe pass over the
# fleet (the same probe fleet_pick_host makes), sorted by 1-minute load; a box that does not answer
# or is not prepared is skipped, not chosen; the excluded boxes (the primary, and anything the caller
# already holds) are never returned. Prints up to $1 hosts, one per line — FEWER when the fleet is
# short, and the caller decides what a short fleet means (land-remote.sh degrades to an unsharded
# landing and says so; it does not launch three shards and call it four).
fleet_pick_hosts() { # $1 = how many  $2.. = hosts to exclude
  local want="$1"; shift
  local hosts h probe ex skip rows=""
  hosts="$(fleet_hosts)"
  for h in $hosts; do
    skip=0; for ex in "$@"; do [ "$h" = "$ex" ] && skip=1; done; [ "$skip" = 1 ] && continue
    probe="$(_fleet_tmo 15 "$SSH_WRAP" "$REMOTE_USER@$h" 'test -d ~/busbar.git && test -d ~/busbar-prove && cut -d" " -f1 /proc/loadavg' </dev/null 2>/dev/null || true)"
    case "$probe" in ''|*[!0-9.]*) rlog "fleet: $h skipped (unreachable or unprepared)"; continue ;; esac
    rows="$rows$probe $h
"
  done
  printf '%s' "$rows" | sort -n | head -n "$want" | awk '{print $2}'
}

# Push ONE NAMED COMMIT (not HEAD) into a box's bare repo under a ref of the caller's choosing. The
# fan-out needs it because the tree a shard must prove is the primary box's cherry-picked tip, which
# this repository only holds after fetching it from the primary — it is nobody's HEAD here.
remote_push_sha() { # $1 = host  $2 = local repo  $3 = ref name  $4 = sha
  local host="$1" repo="$2" ref="$3" sha="$4"
  GIT_SSH_COMMAND="$SSH_WRAP" git -C "$repo" push -q --force \
    "ssh://$REMOTE_USER@$host/~/$REMOTE_BARE" "+$sha:refs/heads/$ref"
}

# A REQUEST LINE, as the primary's land.sh writes it (`land_shard_request`): `gate=G n=N sha=S ref=R
# ceil=VAR=SECS`. Parsed into R_gate R_n R_sha R_ref R_ceil, and REFUSED — return 1 — when any field
# is missing or malformed, because a request the laptop half-understood would launch shards of the
# wrong tree or the wrong count, and the union check would then be RED for a reason nobody could name.
fanout_parse_request() { # $1 = the line
  local f
  R_gate=""; R_n=""; R_sha=""; R_ref=""; R_ceil=""
  for f in $1; do
    case "$f" in
      gate=*) R_gate="${f#gate=}" ;;
      n=*)    R_n="${f#n=}" ;;
      sha=*)  R_sha="${f#sha=}" ;;
      ref=*)  R_ref="${f#ref=}" ;;
      ceil=*) R_ceil="${f#ceil=}" ;;
      *) return 1 ;;
    esac
  done
  [ -n "$R_gate" ] && [ -n "$R_ref" ] || return 1
  case "$R_n" in ''|*[!0-9]*) return 1 ;; esac
  [ "$R_n" -ge 2 ] && [ "$R_n" -le 4 ] || return 1
  case "$R_sha" in *[!0-9a-f]*|'') return 1 ;; esac
  [ "${#R_sha}" -eq 40 ] || return 1
  case "$R_ceil" in *=*) ;; *) return 1 ;; esac
  case "${R_ceil#*=}" in ''|*[!0-9]*) return 1 ;; esac
  return 0
}

# EVERY ARGUMENT IS QUOTED FOR THE REMOTE SHELL. ssh does not exec an argv; it concatenates what it
# is given and hands the STRING to the login shell, which then re-splits and re-globs it. An oracle
# id-filter is a regex — `^(billing|ledger)([|.]|$)` — and unquoted that is a subshell, a pipeline
# and a glob before it ever reaches the proof. Observed, first run: `syntax error near unexpected
# token ('`. `printf %q` is the quoting the remote bash will undo exactly.
_rq() { local out="" a; for a in "$@"; do out="$out $(printf '%q' "$a")"; done; printf '%s' "${out# }"; }
rsh()        { local h="$1"; shift; "$SSH_WRAP" "$REMOTE_USER@$h" "$(_rq "$@")"; }
rsh_script() { local h="$1"; shift; "$SSH_WRAP" -T "$REMOTE_USER@$h" "bash -s -- $(_rq "$@")"; }
rcp_back()   { scp -q -S "$SSH_WRAP" "$REMOTE_USER@$1:$2" "$3"; }
rcp_to()     { scp -q -S "$SSH_WRAP" "$2" "$REMOTE_USER@$1:$3"; }

# ── One-time (and idempotent) preparation of a box ──────────────────────────────────────────────
# A BARE REPO AND A SEPARATE CHECKOUT, not one non-bare repo. Pushing into a non-bare repo's
# checked-out branch is refused by git for a good reason, and `receive.denyCurrentBranch=false`
# buys that refusal off by letting a push desynchronise the index from HEAD — which shows up later
# as a proof run against a tree that is not the one that was pushed. The bare repo takes the push;
# the checkout is reset to it explicitly, by the same script that then runs the proof.
remote_setup() { # $1 = host
  local host="$1"
  rlog "preparing $host: bare ~/$REMOTE_BARE + checkout ~/$REMOTE_WORK"
  rsh_script "$host" <<'SETUP'
set -uo pipefail
export PATH="$HOME/.cargo/bin:$PATH"
BARE="$HOME/busbar.git"
WORK="$HOME/busbar-prove"
if [ ! -d "$BARE" ]; then
  # SEEDED FROM GITHUB, NOT `git init --bare`. An empty bare repo means the operator's first
  # `push HEAD` carries the ENTIRE history over the SSM tunnel: measured at many minutes of
  # nothing-happening, ending in `unexpected disconnect while reading sideband packet` — which
  # reads exactly like a hung transport and is really a cold repository. The box has a fast,
  # direct link to github.com; let it fetch its own objects, and every push after is a delta.
  git clone --bare -q https://github.com/GetBusbar/busbar.git "$BARE" || exit 1
  git -C "$BARE" config gc.auto 256
fi
# Kept current for the same reason: a bare repo a week behind makes the next push a week of objects.
git -C "$BARE" fetch -q --prune origin "+refs/heads/*:refs/heads/*" 2>/dev/null || true
if [ ! -d "$WORK/.git" ]; then
  # Cloned from the bare repo (which the block above has just seeded), so the box downloads the
  # history once and the checkout is a local hardlink copy. The objects and the warm target/ are the
  # two things that make a persistent box worth having over a fresh container.
  git clone -q "$BARE" "$WORK" || exit 1
  git -C "$WORK" remote rename origin prove 2>/dev/null || git -C "$WORK" remote add prove "$BARE"
fi
git -C "$WORK" remote get-url prove >/dev/null 2>&1 || git -C "$WORK" remote add prove "$BARE"
git -C "$WORK" config user.name  "busbar remote prove"
git -C "$WORK" config user.email "ci@busbar.invalid"
git -C "$WORK" config advice.detachedHead false
if [ -f "$WORK/rust-toolchain.toml" ]; then
  ch=$(sed -n 's/^channel[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$WORK/rust-toolchain.toml" | head -1)
  [ -n "$ch" ] && rustup toolchain install "$ch" -c clippy -c rustfmt >/dev/null 2>&1
fi
sudo install -d -m 0777 -o ubuntu /var/cache/sccache 2>/dev/null || true
docker info >/dev/null 2>&1 || echo "WARNING: docker is not usable by $(id -un)" >&2
printf 'READY %s\n  cargo   %s\n  rustc   %s\n  sccache %s\n  docker  %s\n' \
  "$(hostname)" "$(cargo --version 2>&1)" "$(rustc --version 2>&1)" \
  "$(sccache --version 2>&1)" "$(docker --version 2>&1)"
SETUP
}

# Push the local tip (and any extra commit-ish the caller names — a batch's picks live in agent
# worktrees and are not reachable from HEAD) into the box's bare repo. Refs are namespaced by a
# per-run tag so two concurrent proofs on one box cannot overwrite each other mid-checkout.
remote_push_tree() { # $1 = host  $2 = local repo  $3 = ref name  $4.. = extra commit-ish
  local host="$1" repo="$2" ref="$3"; shift 3
  local -a specs=( "+HEAD:refs/heads/$ref" )
  local h
  for h in "$@"; do
    [ -n "$h" ] || continue
    specs+=( "+$h:refs/proof/$ref/$h" )
  done
  # THE AUDIT PINS TRAVEL TOO. qa/audit-ledger.json records the commit each audit round read
  # (`audited_at`), and the audit-ledger gate re-derives that tree with `git ls-tree`. Those commits
  # are audit worktree pins, not ancestors of the tree, so a fresh clone cannot resolve them and the
  # gate is red for a reason that has nothing to do with the landing. The integrator keeps a local
  # ref per pin under refs/audit-pins/<sha> (mirrored to origin refs/backup/audit-pins/); they ride
  # along on every push so the box can produce the same trees the laptop can.
  local pin
  for pin in $(git -C "$repo" for-each-ref --format='%(refname)' refs/audit-pins/ 2>/dev/null); do
    specs+=( "+$pin:$pin" )
  done
  rlog "pushing $(git -C "$repo" rev-parse --short HEAD) and ${#} extra object(s) to $host"
  GIT_SSH_COMMAND="$SSH_WRAP" git -C "$repo" push -q --force \
    "ssh://$REMOTE_USER@$host/~/$REMOTE_BARE" "${specs[@]}" \
    || rdie "push to $host failed — prepare the box with ./scripts/prove-remote.sh --setup $host"
}

# ──────────────────────────────────────────────────────────────────────────────────────────────────
# --selftest, when this file is EXECUTED rather than sourced: the allocator's choices against a
# stub fleet, and the request parser's refusals. The stub wrapper stands in for ~/.busbar-fleet-ssh
# and answers per host from a table, so "least loaded", "unprepared", "silent" and "excluded" are
# each a box in the table rather than a fact about the live fleet.
# ──────────────────────────────────────────────────────────────────────────────────────────────────
_lib_selftest() {
  local root fails=0
  root="$(mktemp -d "${TMPDIR:-/tmp}/ci-remote-lib-selftest.XXXXXX")"
  _t() { if [ "$2" = "$3" ]; then printf '  ok   %-52s\n' "$1"; else printf '  FAIL %-52s (wanted [%s], got [%s])\n' "$1" "$2" "$3"; fails=$((fails + 1)); fi; }
  printf 'box-a\nbox-b\nbox-c\nbox-d\nbox-e\n# a comment\n' >"$root/fleet"
  # The stub: box-a load 4.5, box-b unprepared (prints nothing), box-c load 1.0, box-d hangs, box-e load 2.0.
  cat >"$root/ssh" <<'STUB'
#!/bin/sh
for a in "$@"; do case "$a" in ubuntu@*) h="${a#ubuntu@}" ;; esac; done
case "$h" in
  box-a) echo 4.50 ;;
  box-b) exit 1 ;;
  box-c) echo 1.00 ;;
  box-d) sleep 60 ;;
  box-e) echo 2.00 ;;
esac
STUB
  chmod +x "$root/ssh"
  FLEET_FILE="$root/fleet"; SSH_WRAP="$root/ssh"
  _fleet_tmo() { if command -v timeout >/dev/null 2>&1; then timeout "$@"; elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$@"; else shift; "$@"; fi; }
  echo "ci-remote-lib selftest: the allocator (distinct, least loaded, prepared, never the excluded)"
  _t "three boxes, least loaded first"  "$(printf 'box-c\nbox-e\nbox-a')" "$(_fleet_tmo() { shift; [ "$1" = "$SSH_WRAP" ] && { case "$*" in *box-d*) return 1 ;; esac; }; "$@"; }; fleet_pick_hosts 3 2>/dev/null)"
  _t "the primary is never chosen"      "$(printf 'box-c\nbox-a')"        "$(_fleet_tmo() { shift; case "$*" in *box-d*) return 1 ;; esac; "$@"; }; fleet_pick_hosts 2 box-e 2>/dev/null)"
  _t "a short fleet returns FEWER, not a repeat" "$(printf 'box-c')"      "$(_fleet_tmo() { shift; case "$*" in *box-d*) return 1 ;; esac; "$@"; }; fleet_pick_hosts 3 box-a box-e 2>/dev/null)"
  _t "the silent box is skipped, and named" 1 "$(_fleet_tmo() { shift; case "$*" in *box-d*) return 1 ;; esac; "$@"; }; fleet_pick_hosts 4 2>&1 >/dev/null | grep -c 'box-d skipped')"
  echo "ci-remote-lib selftest: the request parser (a request half-understood is refused)"
  local sha; sha="$(printf '%040d' 7)"
  _t "a well-formed request parses"     0 "$(fanout_parse_request "gate=kind-isolation n=4 sha=$sha ref=shardreq-1 ceil=X=3600"; echo $?)"
  _t "  ...and yields its fields"       "kind-isolation 4 shardreq-1 3600" "$(fanout_parse_request "gate=kind-isolation n=4 sha=$sha ref=shardreq-1 ceil=X=3600"; echo "$R_gate $R_n $R_ref ${R_ceil#*=}")"
  _t "a short sha is refused"           1 "$(fanout_parse_request "gate=g n=4 sha=abc ref=r ceil=X=1"; echo $?)"
  _t "n above four is refused"          1 "$(fanout_parse_request "gate=g n=5 sha=$sha ref=r ceil=X=1"; echo $?)"
  _t "n of one is refused"              1 "$(fanout_parse_request "gate=g n=1 sha=$sha ref=r ceil=X=1"; echo $?)"
  _t "a missing gate is refused"        1 "$(fanout_parse_request "n=4 sha=$sha ref=r ceil=X=1"; echo $?)"
  _t "an unknown field is refused"      1 "$(fanout_parse_request "gate=g n=4 sha=$sha ref=r ceil=X=1 extra=1"; echo $?)"
  _t "a ceiling that is not seconds is refused" 1 "$(fanout_parse_request "gate=g n=4 sha=$sha ref=r ceil=X=soon"; echo $?)"
  rm -rf "$root"
  if [ "$fails" -eq 0 ]; then echo "ci-remote-lib selftest: GREEN (allocator, request parser)"; return 0; fi
  echo "ci-remote-lib selftest: RED ($fails failure(s))" >&2; return 1
}
if [ "${BASH_SOURCE[0]}" = "$0" ] && [ "${1:-}" = "--selftest" ]; then _lib_selftest; exit $?; fi
