// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors
//
// THE BOTH-WAYS FIXTURE TABLE (test builds include it; nothing else reads it). Which in-tree plugin
// proves each kind both ways is DATA in `Cargo.toml`:
//
//   [package.metadata.busbar.both-ways]   <kind> = "<fixture crate>"
//
// A HOT kind's row (`HOT_KINDS`) goes to `HOT_FIXTURES` instead of the cold entry table.
// and this turns the rows into `$OUT_DIR/both_ways.rs`: `(kind, the fixture's cdylib crate name, its
// linked entry)` per row, in manifest order, and `<kind>_fixture` — the fixture crate itself, for a
// test that drives its compiled-in twin (`open` + `dispatch_compiled_in`). `src/tests/both_ways.rs`
// includes it, so the conformance tests reach each fixture by KIND and no test source names a plugin
// instance. Each row is ALSO written alone to `$OUT_DIR/fixture_<kind>.rs` (`<kind>_fixture` and
// `<KIND>_FIXTURE_CDYLIB`), for a test target that links that one fixture only. The loader tests the
// axis, and a plugin tests itself (DECISIONS #2). The same shape as the composition root's linked
// tables (`crates/busbar/src/linked_gen.rs`): one row per line, both sides optionally double-quoted.
// Reads only this crate's own manifest.

use std::env;
use std::path::PathBuf;

/// The kinds whose fixture carries a door or a `#[repr(C)]` decl, not a cold entry (plane, transport
/// and the memory-ABI secret kind).
const HOT_KINDS: &[&str] = &["plane", "transport", "secret"];

/// The rows whose fixture is on its kind's MEMORY ABI: the linked door is the fixture's
/// `door::door` (THE DESIGN, compiled-in = dropped-in: the same door its dropped-in build exports),
/// not a cold entry.
const DOOR_ROWS: &[&str] = &["auth", "auth-verify"];

/// The rows whose fixture is reached only by its crate and its door example (`store_door.rs`): no
/// cold entry, no `door::door` (the store kind's door is the crate's own `door`).
const STORE_ROWS: &[&str] = &["store"];

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");
    let manifest = std::fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let mut out = String::from(
        "// @generated by build.rs from Cargo.toml `[package.metadata.busbar.both-ways]`.\n\
         /// `(kind, cdylib crate name, linked entry)` of each cold kind's both-ways fixture.\n\
         #[allow(dead_code)]\n\
         pub(crate) static FIXTURES: &[(&str, &str, &busbar_contract::abi::cold::ColdEntry)] = &[\n",
    );
    let mut crates = String::new();
    // A HOT kind's row: its fixture has no cold entry — its linked door is its `#[repr(C)]` decl — so
    // it contributes its crate alias and its cdylib name only.
    let mut hot = String::from(
        "/// `(kind, cdylib crate name)` of each HOT kind's both-ways fixture.\n\
         #[allow(dead_code)]\n\
         pub(crate) static HOT_FIXTURES: &[(&str, &str)] = &[\n",
    );
    // THE STORE FIXTURE, BY KIND, for the targets that cannot include `both_ways.rs` (an integration
    // test, the store v3 door example): `store_fixture.rs` aliases the `store` row's crate and names
    // its cdylib stem; `store_door.rs` is the example's one `export_door!` line. No test or fixture
    // source names the store instance (instance-noun-neutrality, ARCHITECT Q-GG4(c)).
    let mut store_fixture = String::new();
    let mut store_door = String::new();
    // A memory-ABI row: its fixture's door.
    let mut doors = String::from(
        "/// `(row, cdylib crate name, linked door)` of each memory-ABI both-ways fixture.\n\
         pub(crate) static DOOR_FIXTURES: &[(&str, &str, busbar_contract::abi::mechanism::door::DoorFn)] = &[\n",
    );
    let mut in_table = false;
    for line in manifest.lines() {
        let code = line.split('#').next().unwrap_or("").trim();
        if code.starts_with('[') {
            in_table = code == "[package.metadata.busbar.both-ways]";
            continue;
        }
        if let (true, Some((kind, krate))) = (in_table, code.split_once('=')) {
            let kind = kind.trim().trim_matches('"');
            let snake = krate.trim().trim_matches('"').replace('-', "_");
            // The row's cdylib crate name as `BUSBAR_BOTH_WAYS_<KIND>`, for the `test-support`
            // harness (`src/test_support.rs`), which is compiled without the dev-dependencies the
            // table above names and so reaches its fixture's artifact by this name alone.
            println!(
                "cargo:rustc-env=BUSBAR_BOTH_WAYS_{}={snake}",
                kind.to_uppercase().replace('-', "_")
            );
            if HOT_KINDS.contains(&kind) {
                hot.push_str(&format!("    (\"{kind}\", \"{snake}\"),\n"));
            } else if STORE_ROWS.contains(&kind) {
                // Reached by its crate alias and its door example below; no table row.
            } else if DOOR_ROWS.contains(&kind) {
                doors.push_str(&format!(
                    "    (\"{kind}\", \"{snake}\", ::{snake}::door::door),\n"
                ));
            } else {
                out.push_str(&format!(
                    "    (\"{kind}\", \"{snake}\", &::{snake}::BUSBAR_COLD_ENTRY),\n"
                ));
            }
            if kind == "store" {
                store_fixture = format!(
                    "// @generated by build.rs from the `store` both-ways row.\n\
                     /// The `store` both-ways fixture crate, reached by kind.\n\
                     #[allow(unused_imports)]\n\
                     pub use ::{snake} as store_fixture;\n\
                     /// The file stem of its dropped-in `cdylib`.\n\
                     #[allow(dead_code)]\n\
                     pub const STORE_FIXTURE_CDYLIB: &str = \"{snake}\";\n"
                );
                store_door = format!(
                    "// @generated by build.rs from the `store` both-ways row.\n\
                     busbar_contract::export_door!(::{snake}::door);\n"
                );
            }
            // A second proof of one kind is keyed `<kind>-<proof>`; its alias is that key as an ident.
            // A HOT kind's `-plugin` row gets NO alias: nothing names its crate, so the test binary never
            // links its rlib. The row is a dev-dependency only so cargo BUILDS its cdylib, and a
            // `-plugin` crate's rlib exports `busbar_plugin_door` (`export_door!`), which two
            // doors in one fat-LTO unit make "symbol multiply defined". Naming the crate would link it.
            // A row naming the LOGIC crate (no `-plugin` suffix, so no door symbol in its rlib: the
            // `secret` row) is linked as an ordinary fixture crate below.
            if let (true, Some(logic)) = (HOT_KINDS.contains(&kind), snake.strip_suffix("_plugin"))
            {
                // The row's LOGIC crate (the same repo's crate the `-plugin` crate packs; it exports no
                // door symbol) gives the linked door: `<kind>_linked::{door, KEY}`.
                crates.push_str(&format!(
                    "#[allow(unused_imports)]\npub(crate) use ::{logic}::linked as {}_linked;\n",
                    kind.replace('-', "_")
                ));
                continue;
            }
            let alias = kind.replace('-', "_");
            crates.push_str(&format!(
                "// The `{kind}` both-ways fixture crate.\n\
                 #[allow(unused_imports)]\n\
                 pub(crate) use ::{snake} as {alias}_fixture;\n"
            ));
            // The row ALONE, for a test target that must link only this kind's fixture (an example
            // `cdylib` exporting that fixture's door, an integration test): `fixture_<alias>.rs`.
            let upper = alias.to_uppercase();
            let one = format!(
                "// @generated by build.rs: the `{kind}` both-ways fixture row alone.\n\
                 #[allow(unused_imports)]\n\
                 pub use ::{snake} as {alias}_fixture;\n\
                 /// The `{kind}` fixture's cdylib crate name.\n\
                 #[allow(dead_code)]\n\
                 pub const {upper}_FIXTURE_CDYLIB: &str = \"{snake}\";\n"
            );
            let file = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"))
                .join(format!("fixture_{alias}.rs"));
            std::fs::write(file, one).expect("write fixture_<kind>.rs");
        }
    }
    out.push_str("];\n");
    hot.push_str("];\n");
    out.push_str(&hot);
    doors.push_str("];\n");
    out.push_str(&doors);
    out.push_str(&crates);
    let dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(dir.join("both_ways.rs"), out).expect("write both_ways.rs");
    assert!(
        !store_fixture.is_empty(),
        "[package.metadata.busbar.both-ways] has no `store` row: the store fixture has no source"
    );
    std::fs::write(dir.join("store_fixture.rs"), store_fixture).expect("write store_fixture.rs");
    std::fs::write(dir.join("store_door.rs"), store_door).expect("write store_door.rs");
}
