// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors
//
// THE BOTH-WAYS FIXTURE TABLE (test builds include it; nothing else reads it). Which in-tree plugin
// proves each kind both ways is DATA in `Cargo.toml`:
//
//   [package.metadata.busbar.both-ways]   <kind> = "<fixture crate>"
//
// A HOT kind's row (`HOT_KINDS`) goes to `HOT_FIXTURES` instead of the cold entry table.
// and this turns the rows into `$OUT_DIR/both_ways.rs`: `(kind, the fixture's cdylib crate name, its
// linked entry)` per row, in manifest order, and `<kind>_fixture` — the fixture crate itself, for a
// test that drives its compiled-in twin (`open` + `dispatch_compiled_in`). `src/tests/both_ways.rs`
// includes it, so the conformance tests reach each fixture by KIND and no test source names a plugin
// instance — the loader tests the
// axis, and a plugin tests itself (DECISIONS #2). The same shape as the composition root's linked
// tables (`crates/busbar/src/linked_gen.rs`): one row per line, both sides optionally double-quoted.
// Reads only this crate's own manifest.

use std::env;
use std::path::PathBuf;

/// The HOT-lane kinds (#30): their fixtures carry a `#[repr(C)]` decl, not a cold entry.
const HOT_KINDS: &[&str] = &["plane", "transport"];

/// The rows whose fixture is on its kind's MEMORY ABI: the linked door is the fixture's
/// `door::door` (THE DESIGN, compiled-in = dropped-in: the same door its dropped-in build exports),
/// not a cold entry.
const DOOR_ROWS: &[&str] = &["auth-verify"];

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");
    let manifest = std::fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let mut out = String::from(
        "// @generated by build.rs from Cargo.toml `[package.metadata.busbar.both-ways]`.\n\
         /// `(kind, cdylib crate name, linked entry)` of each cold kind's both-ways fixture.\n\
         pub(crate) static FIXTURES: &[(&str, &str, &busbar_contract::abi::cold::ColdEntry)] = &[\n",
    );
    let mut crates = String::new();
    // A HOT kind's row: its fixture has no cold entry — its linked door is its `#[repr(C)]` decl — so
    // it contributes its crate alias and its cdylib name only.
    let mut hot = String::from(
        "/// `(kind, cdylib crate name)` of each HOT kind's both-ways fixture.\n\
         #[allow(dead_code)]\n\
         pub(crate) static HOT_FIXTURES: &[(&str, &str)] = &[\n",
    );
    // A memory-ABI row: its fixture's door.
    let mut doors = String::from(
        "/// `(row, cdylib crate name, linked door)` of each memory-ABI both-ways fixture.\n\
         pub(crate) static DOOR_FIXTURES: &[(&str, &str, busbar_contract::abi::mechanism::door::DoorFn)] = &[\n",
    );
    let mut in_table = false;
    for line in manifest.lines() {
        let code = line.split('#').next().unwrap_or("").trim();
        if code.starts_with('[') {
            in_table = code == "[package.metadata.busbar.both-ways]";
            continue;
        }
        if let (true, Some((kind, krate))) = (in_table, code.split_once('=')) {
            let kind = kind.trim().trim_matches('"');
            let snake = krate.trim().trim_matches('"').replace('-', "_");
            if HOT_KINDS.contains(&kind) {
                hot.push_str(&format!("    (\"{kind}\", \"{snake}\"),\n"));
            } else if DOOR_ROWS.contains(&kind) {
                doors.push_str(&format!(
                    "    (\"{kind}\", \"{snake}\", ::{snake}::door::door),\n"
                ));
            } else {
                out.push_str(&format!(
                    "    (\"{kind}\", \"{snake}\", &::{snake}::BUSBAR_COLD_ENTRY),\n"
                ));
            }
            // A second proof of one kind is keyed `<kind>-<proof>`; its alias is that key as an ident.
            let alias = kind.replace('-', "_");
            crates.push_str(&format!(
                "// The `{kind}` both-ways fixture crate.\n\
                 #[allow(unused_imports)]\n\
                 pub(crate) use ::{snake} as {alias}_fixture;\n"
            ));
        }
    }
    out.push_str("];\n");
    hot.push_str("];\n");
    out.push_str(&hot);
    doors.push_str("];\n");
    out.push_str(&doors);
    out.push_str(&crates);
    let path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("both_ways.rs");
    std::fs::write(path, out).expect("write both_ways.rs");
}
