// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Busbar Inc and contributors

//! THE FIELD COVERAGE GATE. Every request, response and stream path of every chat dialect busbar
//! speaks is either `carried` (with a named test that fails if it stops being carried), `waived`
//! (with a dated reason), or **UNCLASSIFIED — and the UNCLASSIFIED set is pinned, so it fails the
//! build the moment it changes in either direction.**
//!
//! Owner's ruling, 2026-08-13, and it is the whole reason this file exists:
//!
//! > *"good fix it all. IR completion is key. we say we dont leave things on floor, its our
//! > differentiator. needs to be solid"*
//!
//! ## Why a gate and not a fixed list of defects
//!
//! The 1.6.0 IR-losslessness audit ranked six losses. Its most important finding was not any of
//! them — it was the reason they went unnoticed: **the exposure lived in fields that are never read
//! and never emitted.** A mutation pass renamed eight writer-emitted keys and all eight were caught
//! by name; meanwhile audio attachments, usage sub-buckets and citation offsets were being dropped
//! in silence, because **you cannot mutate a field that does not exist.**
//!
//! So a list of six is a list of six things somebody happened to notice. This gate makes the CLASS
//! enumerable, exactly as the method-coverage gate does for protocol methods, and
//! for the reason `scripts/method-inventory.py` states: a hand-written list is how coverage ends at
//! J with nobody noticing, because an absent row and a considered-and-inapplicable row look
//! identical on the page.
//!
//! ## The inputs, none of which is prose
//!
//! | file | what it is | who writes it |
//! |---|---|---|
//! | `testing/llm-conformance/wire/<d>.wire.json` | every request, response and stream path of every dialect | GENERATED by `cargo xtask dialect wire --write` from the specs pinned in `testing/llm-conformance/spec-digests.tsv` |
//! | `qa/field-coverage.status` | the `carried` / `waived` claims | a human, one line per field, a TEST NAME on every `carried` and a dated reason on every waiver |
//! | `qa/field-coverage.missing` | the pinned, ranked UNCLASSIFIED-NEW list | a human, deliberately, by reading a diff |
//! | `qa/field-coverage.offspec` | status ids the wire has and the spec root lacks, each with its reason | a human |
//!
//! All four are read through ONE function, [`common::coverage::classify`], so every caller (this
//! gate, the dialect mapping files' row checks) classifies a field the same way.
//!
//! ## `carried` means an instrument watched it
//!
//! A `carried` line names a test function, and [`every_carried_claim_names_a_real_test`] fails if
//! that function does not exist in the tree. **A field a test would not miss is a field the next
//! edit drops silently** — which is precisely how the audited six arrived. This is the same bar the
//! method matrix holds: a cell counts only if an instrument was watched saying so.
//!
//! ## Why the pinned list is long, and why that is the deliverable
//!
//! The hand-copied lists this gate used to read named 412 fields; the pinned provider specs hold
//! several thousand. Claiming the rest on the strength of "the reader looks like it handles that"
//! would be claiming coverage the release does not have — the exact move this gate exists to make
//! impossible. So every unbacked path is UNCLASSIFIED, `qa/field-coverage.missing` pins it in rank
//! order, and the pin is the carry work queue: no field lands without editing that file.
//!
//! The repo's convention for a deliberately-red gate: *"a suite whose result is UNCHANGING is still
//! a gate, because the thing a gate has to catch is a CHANGE."*
//!
//! **Never weaken this gate to make it green.** Do not move a line from `.missing` to a waiver to
//! make a number look better: a waiver says "not owed, and here is why", and laundering a gap into
//! one is how the losslessness claim became false in the first place.

mod common;

use std::collections::BTreeSet;

use common::coverage::{self, classify, TIERS};

/// Every id named in the status file is a wire-lock path or a named OFF-SPEC id, and every OFF-SPEC
/// id is NOT in the locks and IS claimed in the status file.
///
/// The failure this catches is a claim that outlives its field: a provider renames something, the
/// lock follows, and a stale `carried` line goes on asserting coverage of a field nobody can send
/// any more — which inflates the covered count with a fiction.
#[test]
fn every_status_line_names_a_real_field() {
    let cov = classify();
    let ids = cov.ids();
    let unknown: Vec<&String> = cov
        .status
        .keys()
        .filter(|k| !ids.contains(k.as_str()) && !cov.offspec.contains_key(*k))
        .collect();
    assert!(
        unknown.is_empty(),
        "{} names field(s) that are in no wire lock and not OFF-SPEC. Either the spec moved \
         (cargo xtask dialect wire --diff all names the rename) or the line is stale:\n{unknown:#?}",
        coverage::STATUS
    );
    let stale_offspec: Vec<&String> = cov
        .offspec
        .keys()
        .filter(|k| ids.contains(k.as_str()) || !cov.status.contains_key(*k))
        .collect();
    assert!(
        stale_offspec.is_empty(),
        "{} lists id(s) that are now in a wire lock (move the claim to the lock path) or that no \
         status line claims:\n{stale_offspec:#?}",
        coverage::OFFSPEC
    );
}

/// THE PINNED UNCLASSIFIED-NEW LIST must EXACTLY equal the computed one, in both directions AND in
/// rank order (request fields, block types, stream events, response fields, stream fields; then
/// shallower first), so the file reads as the carry work queue it is.
///
/// * a field pinned here that is now `carried`/`waived` → red. Delete the line in the same commit
///   that lands the coverage, so the queue shrinks visibly.
/// * a field the locks gained (a provider added a member, block type or event) → red, because it
///   is not listed here: classify it or pin it, on purpose.
#[test]
fn pinned_missing_set_is_exact() {
    let cov = classify();
    let computed: Vec<&str> = cov
        .unclassified()
        .into_iter()
        .map(|w| w.id.as_str())
        .collect();
    let want: BTreeSet<&str> = computed.iter().copied().collect();
    let pinned: BTreeSet<&str> = cov.pinned.iter().map(String::as_str).collect();
    let newly_missing: Vec<&&str> = want.difference(&pinned).collect();
    let no_longer_missing: Vec<&&str> = pinned.difference(&want).collect();
    assert!(
        newly_missing.is_empty(),
        "field(s) are UNCLASSIFIED that {} does not pin. Classify them in {} (with a test, or a \
         dated waiver reason) or pin them in rank order — never leave a field unclassified, \
         because an unclassified field is exactly a field nobody is watching:\n{newly_missing:#?}",
        coverage::MISSING,
        coverage::STATUS
    );
    assert!(
        no_longer_missing.is_empty(),
        "field(s) pinned as UNCLASSIFIED are now classified (or left the locks) — delete these \
         lines from {} in the same commit, so the work queue shrinks visibly:\n\
         {no_longer_missing:#?}",
        coverage::MISSING
    );
    let first_out_of_rank = cov.pinned.iter().zip(&computed).position(|(p, c)| p != c);
    assert_eq!(
        first_out_of_rank,
        None,
        "{} is not in rank order at its entry {:?}; the computed order puts {:?} there",
        coverage::MISSING,
        first_out_of_rank.map(|i| &cov.pinned[i]),
        first_out_of_rank.map(|i| computed[i])
    );
}

/// THE UNCLASSIFIED-NEW REPORT: counts per dialect and rank tier (`-- --nocapture` prints it). The
/// list is the #76 carry work queue; the counts are what the carry lanes are staffed from.
#[test]
fn unclassified_new_report() {
    let cov = classify();
    let open = cov.unclassified();
    let mut counts: std::collections::BTreeMap<(&str, usize), usize> = Default::default();
    for w in &open {
        *counts.entry((w.dialect(), w.tier())).or_default() += 1;
    }
    println!(
        "UNCLASSIFIED-NEW: {} of {} wire paths ({} classified)",
        open.len(),
        cov.wire.len(),
        cov.wire.len() - open.len()
    );
    let dialects: BTreeSet<&str> = cov.wire.iter().map(|w| w.dialect()).collect();
    for d in dialects {
        let row: Vec<String> = TIERS
            .iter()
            .enumerate()
            .map(|(i, t)| format!("{t} {}", counts.get(&(d, i)).copied().unwrap_or(0)))
            .collect();
        println!("  {d}: {}", row.join(", "));
    }
    assert!(
        open.len() < cov.wire.len(),
        "nothing is classified: the status file and the locks share no id"
    );
}

/// FULL-STRENGTH ACCEPTANCE: every wire path is carried or waived, and nothing is UNCLASSIFIED.
///
/// Kept at full strength and `#[ignore]`d rather than weakened, exactly as
/// the method-coverage acceptance test is. Run it with `-- --ignored`.
#[test]
#[ignore = "acceptance: the field work queue in qa/field-coverage.missing is the deliverable, and \
            a visible red queue is the honest shape of a partial sweep"]
fn every_field_is_carried_or_waived() {
    let cov = classify();
    let open: Vec<&str> = cov
        .unclassified()
        .into_iter()
        .map(|w| w.id.as_str())
        .collect();
    assert!(
        open.is_empty(),
        "{} field(s) are neither carried nor waived:\n{open:#?}",
        open.len()
    );
}
