#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Busbar Inc and contributors
#
# Prove the LLM spec conformance rig cannot pass vacuously, before any verdict from it is trusted.
# Every case goes through run.sh (vendor -> validate -> verdict), the real pipeline, with the tiny
# tracked fixture under fixtures/selftest-recording (three 1.5.5 cells that validate cleanly):
#
#   (a) the known-good fixture                       -> GREEN, every owed row PASS
#   (b) one response field's TYPE mutated            -> RED, exactly one FAIL, naming the pointer
#   (c) one SSE event field's TYPE mutated           -> RED, exactly one FAIL, naming sse[N]:/pointer
#   (d) one REQUEST field's TYPE mutated             -> RED, exactly one FAIL, on the #request row
#   (e) an empty recording directory                 -> RED, the vacuous-run ("zero rows") verdict
#   (f) a cell present in cells.json but not recorded -> a named SKIP, never a PASS, and RED:
#       the gap is coverage that went away and named-gaps.json does not admit it
#   (f2) the same gap NAMED in named-gaps.json with an owner, a rationale and a count -> GREEN,
#       the rows still SKIP and still out of the owed set; what changed is that somebody signed
#   (f3) one gap MORE than the declared count, inside an entry that already names it -> RED. The
#       naming cannot see this one; it is the whole reason there is also a count.
#
# A second tiny tracked fixture, fixtures/selftest-errors-recording (regenerated by
# fixtures/gen-errors-fixture.py; six gemini cells: ok_stream_array + all five error outcomes),
# proves two more things the first fixture does not exercise:
#
#   (g) gemini `ok_stream_array` (a stream requested WITHOUT ?alt=sse; per the Gemini API this is
#       served as a JSON ARRAY of GenerateContentResponse objects, not one object and not SSE)
#       -> GREEN: the array is judged element-by-element against GenerateContentResponse instead of
#          being rejected outright as "expected object, got array"
#   (h) one element of that array given a malformed field                -> RED, exactly one FAIL
#       naming the array index (e.g. `/1/modelVersion`)
#   (i) every error outcome (malformed, unauthenticated, out_of_scope, over_budget, upstream_down)
#       -> GREEN as shipped: each error body is something the SUCCESS schema would reject outright
#          (closed object, no "error" property), so a PASS here is proof the checker judged it
#          against the dialect's ERROR envelope, not the success schema
#
# The named-gap list (named-gaps.json) is the one thing here that can turn a red row green, so its
# every arm is planted on a REAL violation the validator made:
#
#   (i) a gap naming that violation      -> the row leaves the owed set as a gap, never as a PASS,
#                                           carrying the owner and the reason
#   (j) a SECOND, unnamed violation on the same row -> still RED (a gap forgives what it names)
#   (k) the same gap where the row is clean        -> RED as stale, before the verdict
#   (l) an entry with no owner and no reason       -> REFUSED at load; nothing is judged
#   (m) an entry whose cell carries a wildcard     -> REFUSED at load; nothing is judged
#
# And the side of 2xx a cell was answered on, which no schema can see:
#
#   (p) a REFUSAL cell answered HTTP 200 with a schema-clean success body -> RED on outcome.status
#   (q) the mirror — a happy-path cell answered with a schema-clean refusal -> RED on outcome.status
#
# And one case about the SPECS themselves rather than the recording:
#
#   (n) a DRIFTED spec cache — the pinned digest's directory holding a document that is no longer
#       what the digest names — must REFUSE, not judge. The verdict of this rig is only worth the
#       document it was measured against, so a body the PINNED spec rejects may never come back
#       green because the cached copy of that spec was widened underneath it.
#
# Needs the vendored specs (run.sh vendors them; cached by digest, so this is offline after once).
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
FIX="${here}/fixtures/selftest-recording"
FIX2="${here}/fixtures/selftest-errors-recording"
W="$(mktemp -d "${TMPDIR:-/tmp}/llm-conformance-selftest.XXXXXX")"
trap 'rm -rf "$W"' EXIT
fails=0
say() { printf '%s  %s\n' "$1" "$2"; [ "$1" = PASS ] || fails=$((fails+1)); }
RUN_ARGS=""   # extra run.sh args for one case (see (n)/(o)); reset by each caller that sets it
run() {  # run <recording> <out> [cells.json] -> rc
  local cells="${3:-$1/cells.json}"
  # shellcheck disable=SC2086
  bash "${here}/run.sh" --recording "$1" --out "$2" --cells "$cells" $RUN_ARGS >"$2.log" 2>&1; echo $?
}
count() { awk -F'\t' -v s="$2" '$2==s{n++} END{print n+0}' "$1/ledger.tsv"; }
fail_rows() { awk -F'\t' '$2=="FAIL"{print $1"\t"$4}' "$1/ledger.tsv"; }

# (a) known-good
rc="$(run "$FIX" "$W/a")"
if [ "$rc" = 0 ] && [ "$(count "$W/a" PASS)" = 7 ] && [ "$(count "$W/a" FAIL)" = 0 ] && [ "$(count "$W/a" SKIP)" = 0 ]; then
  say PASS "(a) known-good fixture -> GREEN, 6/6 rows PASS (+ the named-gaps row)"
else
  say FAIL "(a) known-good fixture rc=$rc pass=$(count "$W/a" PASS) fail=$(count "$W/a" FAIL) skip=$(count "$W/a" SKIP)"; tail -20 "$W/a.log"
fi

# (b) mutate a response field's type: cohere usage.tokens.input_tokens integer -> string
cp -R "$FIX" "$W/b-rec"
python3 - "$W/b-rec/raw/llm__cohere__cohere__request__ok/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d["usage"]["tokens"]["input_tokens"]="11"
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
rc="$(run "$W/b-rec" "$W/b")"
rows="$(fail_rows "$W/b")"
if [ "$rc" != 0 ] && [ "$(count "$W/b" FAIL)" = 1 ] && grep -q $'^llm|cohere|cohere|request|ok#response\t' <<<"$rows" && grep -q '/usage/tokens/input_tokens type' <<<"$rows"; then
  say PASS "(b) one mutated response type -> RED, exactly one FAIL naming /usage/tokens/input_tokens"
else
  say FAIL "(b) mutated response rc=$rc fails=$(count "$W/b" FAIL): $rows"
fi

# (c) mutate one SSE event: cohere content-delta index integer -> string
cp -R "$FIX" "$W/c-rec"
python3 - "$W/c-rec/raw/llm__cohere__cohere__request__ok_stream/body" <<'EOF'
import sys
p=sys.argv[1]; s=open(p).read()
assert '"index":0' in s
open(p,"w").write(s.replace('"index":0','"index":"0"',1))
EOF
rc="$(run "$W/c-rec" "$W/c")"
rows="$(fail_rows "$W/c")"
if [ "$rc" != 0 ] && [ "$(count "$W/c" FAIL)" = 1 ] && grep -q $'^llm|cohere|cohere|request|ok_stream#response\t' <<<"$rows" && grep -q 'sse\[1\]:/index type' <<<"$rows"; then
  say PASS "(c) one mutated SSE event -> RED, exactly one FAIL naming sse[1]:/index"
else
  say FAIL "(c) mutated SSE rc=$rc fails=$(count "$W/c" FAIL): $rows"
fi

# (d) mutate the REQUEST: gemini contents array -> string
cp -R "$FIX" "$W/d-rec"
printf '%s' '{"contents":"ping"}' >"$W/d-rec/raw/llm__gemini__gemini__request__ok/request.body"
rc="$(run "$W/d-rec" "$W/d")"
rows="$(fail_rows "$W/d")"
if [ "$rc" != 0 ] && [ "$(count "$W/d" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|ok#request\t' <<<"$rows" && grep -q '/contents type' <<<"$rows"; then
  say PASS "(d) one mutated request type -> RED, exactly one FAIL on the #request row naming /contents"
else
  say FAIL "(d) mutated request rc=$rc fails=$(count "$W/d" FAIL): $rows"
fi

# (e) empty recording -> vacuous RED
mkdir -p "$W/e-rec"
rc="$(run "$W/e-rec" "$W/e" "$FIX/cells.json")"
if [ "$rc" != 0 ] && [ "$(awk 'NF{n++} END{print n+0}' "$W/e/ledger.tsv")" = 0 ] && grep -q 'VACUOUS RUN' "$W/e.log"; then
  say PASS "(e) empty recording -> RED, vacuous run (zero rows)"
else
  say FAIL "(e) empty recording rc=$rc rows=$(awk 'NF{n++} END{print n+0}' "$W/e/ledger.tsv")"; tail -5 "$W/e.log"
fi

# (f) a cell in the universe that the recording lacks -> 2 named SKIP rows, never a PASS — and,
# because nothing in named-gaps.json admits them, the run is RED. A gap is coverage that went away;
# a run that lost coverage and reported green is the failure this whole rig exists to prevent.
# ONE FILE, TWO SECTIONS, AND BOTH READERS SEE IT. `named-gaps.json` carries `gaps` — the
# violations validate.py forgives on a named row — and `accepted`/`expected` — the SKIP rows run.sh
# reconciles in step 3b. run.sh hands the same path to both. A fixture that carries only the second
# section is REFUSED by the first ("must be an object with a `gaps` list"), validate.py exits 2, and
# the case under test never runs at all. These three fixtures are about the reconciliation only, so
# their `gaps` list is empty — which is a statement, not a formality: no violation is forgiven here.
printf '%s' '{"gaps": [], "expected": 0, "accepted": []}' >"$W/no-gaps.json"
cp -R "$FIX" "$W/f-rec"
rm "$W/f-rec/cells/llm__gemini__gemini__request__ok.json"
RUN_ARGS="--gaps $W/no-gaps.json"
rc="$(run "$W/f-rec" "$W/f")"
RUN_ARGS=""
if [ "$rc" != 0 ] && [ "$(count "$W/f" SKIP)" = 2 ] && [ "$(count "$W/f" PASS)" = 4 ] && grep -q 'named gap' "$W/f/ledger.tsv" \
   && [ "$(wc -l <"$W/f/owed-gaps.txt" | tr -d ' ')" = 2 ] && grep -q 'is a gap NO entry names' "$W/f/ledger.tsv"; then
  say PASS "(f) unrecorded cell -> 2 named SKIP rows (never PASS), and RED because no entry admits them"
else
  say FAIL "(f) unrecorded cell rc=$rc pass=$(count "$W/f" PASS) skip=$(count "$W/f" SKIP) gaps=$(wc -l <"$W/f/owed-gaps.txt" 2>/dev/null | tr -d ' ')"; tail -8 "$W/f.log"
fi

# (f2) the SAME two gaps, named with an owner and a rationale and counted -> GREEN, gap still a gap.
# The rows stay SKIP and stay out of the owed set; what changed is that somebody signed for them.
cat >"$W/gaps-f.json" <<'EOF'
{"gaps": [],
 "expected": 2,
 "accepted": [{"cells": "^llm\\|gemini\\|gemini\\|request\\|ok#(request|response)$",
               "owner": "llm-conformance selftest",
               "rationale": "the selftest deletes this cell from the recording on purpose, to prove a gap can be signed for"}]}
EOF
RUN_ARGS="--gaps $W/gaps-f.json"
rc="$(run "$W/f-rec" "$W/f2")"
RUN_ARGS=""
if [ "$rc" = 0 ] && [ "$(count "$W/f2" SKIP)" = 2 ] && [ "$(count "$W/f2" PASS)" = 5 ] && grep -q 'each named by' "$W/f2/ledger.tsv"; then
  say PASS "(f2) the same two gaps, named and counted -> GREEN, still SKIP, still out of the owed set"
else
  say FAIL "(f2) named gaps rc=$rc pass=$(count "$W/f2" PASS) skip=$(count "$W/f2" SKIP)"; tail -8 "$W/f2.log"
fi

# (f3) one gap MORE than the number that was declared, inside an entry the file already names, so
# the naming alone cannot see it. Only the count can, which is why there is a count.
cp -R "$W/f-rec" "$W/f3-rec"
rm "$W/f3-rec/cells/llm__cohere__cohere__request__ok.json"
cat >"$W/gaps-f3.json" <<'EOF'
{"gaps": [],
 "expected": 2,
 "accepted": [{"cells": "#(request|response)$",
               "owner": "llm-conformance selftest",
               "rationale": "a deliberately broad entry: it names any row, so only the declared COUNT can catch one more gap than was signed for"}]}
EOF
RUN_ARGS="--gaps $W/gaps-f3.json"
rc="$(run "$W/f3-rec" "$W/f3")"
RUN_ARGS=""
if [ "$rc" != 0 ] && [ "$(count "$W/f3" SKIP)" = 4 ] && grep -q '4 gap(s) observed, 2 declared' "$W/f3/ledger.tsv"; then
  say PASS "(f3) a gap inside an entry that already names it, beyond the declared count -> RED on the count"
else
  say FAIL "(f3) gap count rc=$rc skip=$(count "$W/f3" SKIP): $(awk -F'\t' '$1 ~ /named-gaps/{print $2" "$4}' "$W/f3/ledger.tsv")"; tail -8 "$W/f3.log"
fi

# (g) known-good errors fixture: ok_stream_array (valid 2-element array) + all 5 error outcomes
rc="$(run "$FIX2" "$W/g" "$FIX2/cells.json")"
if [ "$rc" = 0 ] && [ "$(count "$W/g" PASS)" = 12 ] && [ "$(count "$W/g" FAIL)" = 0 ] && [ "$(count "$W/g" SKIP)" = 0 ]; then
  say PASS "(g) known-good errors fixture -> GREEN, 11/11 rows PASS (+ the named-gaps row) (ok_stream_array + 5 error outcomes)"
else
  say FAIL "(g) known-good errors fixture rc=$rc pass=$(count "$W/g" PASS) fail=$(count "$W/g" FAIL) skip=$(count "$W/g" SKIP)"; tail -20 "$W/g.log"
fi

# (h) mutate ONE element (index 1) of the ok_stream_array body: modelVersion string -> integer
cp -R "$FIX2" "$W/h-rec"
python3 - "$W/h-rec/raw/llm__gemini__gemini__request__ok_stream_array/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d[1]["modelVersion"]=12345
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
rc="$(run "$W/h-rec" "$W/h" "$FIX2/cells.json")"
rows="$(fail_rows "$W/h")"
if [ "$rc" != 0 ] && [ "$(count "$W/h" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|ok_stream_array#response\t' <<<"$rows" && grep -q '/1/modelVersion type' <<<"$rows"; then
  say PASS "(h) one malformed array element -> RED, exactly one FAIL naming /1/modelVersion"
else
  say FAIL "(h) malformed array element rc=$rc fails=$(count "$W/h" FAIL): $rows"
fi

# ── THE NAMED-GAP LIST, PROVEN ON BOTH SIDES ────────────────────────────────────────────────────
# named-gaps.json turns a violation the owner has ruled the vendor's schema wrong about into the
# rig's named-gap status instead of a FAIL. That is the one mechanism here that can make a red run
# green, so every way it could become a bypass is planted and proven refused. The violation used is
# case (b)'s: the cohere response type error, which is REAL — the gap is proven to forgive a finding
# the validator genuinely made, not an imaginary one.
gapfile() { printf '%s' "$2" >"$W/$1.json"; echo "$W/$1.json"; }
run_gaps() {  # run_gaps <recording> <out> <cells> <gapfile> -> rc
  bash "${here}/run.sh" --recording "$1" --out "$2" --cells "$3" --named-gaps "$4" >"$2.log" 2>&1; echo $?
}
# The file carries BOTH sections, because a row this list turns from FAIL into a gap is a SKIP row
# like any other and so must also be inside the declared ceiling ((f)-(f3) above). One forgives the
# violation; the other says how many forgiven rows a run may have.
GAP_OK='{"gaps":[{"id":"selftest-cohere-usage","owner":"the selftest","rule":"type",
  "detail_contains":"expected number, got string",
  "cells":["llm|cohere|cohere|request|ok#response"],
  "why":"a planted gap used only by the selftest, to prove a named violation leaves the owed set as a gap and never as a pass"}],
  "expected":1,
  "accepted":[{"cells":"^llm\\|cohere\\|cohere\\|request\\|ok#response$","owner":"the selftest",
               "rationale":"the one row the planted gap above forgives; declared here so the forgiven row is inside the ceiling as well as named"}]}'

# (i) a gap naming the one real violation -> that row is a named gap, the run is GREEN, and the
#     reason and owner travel with it
g="$(gapfile ok "$GAP_OK")"
rc="$(run_gaps "$W/b-rec" "$W/i" "$W/b-rec/cells.json" "$g")"
if [ "$rc" = 0 ] && [ "$(count "$W/i" FAIL)" = 0 ] && [ "$(count "$W/i" SKIP)" = 1 ] \
   && grep -q 'selftest-cohere-usage (the selftest)' "$W/i/ledger.tsv" \
   && grep -qx 'llm|cohere|cohere|request|ok#response' "$W/i/owed-gaps.txt"; then
  say PASS "(i) a named gap on a real violation -> GREEN, the row is a gap (never a PASS), owner and reason carried"
else
  say FAIL "(i) named gap rc=$rc fail=$(count "$W/i" FAIL) skip=$(count "$W/i" SKIP)"; tail -10 "$W/i.log"
fi

# (j) THE SAME GAP, plus a SECOND violation on the same row it does not name -> still FAIL. A gap
#     forgives what it names and nothing else, which is the difference between a gap and a mute.
cp -R "$W/b-rec" "$W/j-rec"
python3 - "$W/j-rec/raw/llm__cohere__cohere__request__ok/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d["id"]=12345
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
rc="$(run_gaps "$W/j-rec" "$W/j" "$W/j-rec/cells.json" "$g")"
if [ "$rc" != 0 ] && [ "$(count "$W/j" FAIL)" = 1 ] && grep -q '/id type' "$W/j/ledger.tsv" \
   && ! grep -q 'input_tokens' "$W/j/ledger.tsv"; then
  say PASS "(j) an UNNAMED violation on the same row -> still RED; only the named one is forgiven"
else
  say FAIL "(j) partial gap rc=$rc fails=$(count "$W/j" FAIL): $(fail_rows "$W/j")"
fi

# (k) the same gap against the UNMUTATED fixture: the row is judged and comes back clean, so the
#     entry forgives nothing -> STALE, and stale is RED. This is what stops a fixed gap from sitting
#     in the file as the place a future real failure would land unseen.
rc="$(run_gaps "$FIX" "$W/k" "$FIX/cells.json" "$g")"
if [ "$rc" != 0 ] && grep -q 'selftest-cohere-usage' "$W/k/stale-gaps.txt" && grep -q 'STALE NAMED GAPS' "$W/k.log"; then
  say PASS "(k) a gap whose named row comes back clean -> RED as stale, before the verdict"
else
  say FAIL "(k) stale gap rc=$rc stale=$(cat "$W/k/stale-gaps.txt" 2>/dev/null)"; tail -8 "$W/k.log"
fi

# (l) an entry with no owner and a one-word reason -> REFUSED at load; nothing is judged.
g2="$(gapfile anon '{"gaps":[{"id":"anon","rule":"type","detail_contains":"expected number, got string","cells":["llm|cohere|cohere|request|ok#response"],"why":"because"}]}')"
rc="$(run_gaps "$W/b-rec" "$W/l" "$W/b-rec/cells.json" "$g2")"
if [ "$rc" != 0 ] && grep -q 'REFUSED named gap' "$W/l.log" && grep -q 'no .owner.' "$W/l.log" \
   && [ "$(awk 'NF{n++} END{print n+0}' "$W/l/ledger.tsv")" = 0 ]; then
  say PASS "(l) a gap with no owner and no reason -> REFUSED at load, nothing judged"
else
  say FAIL "(l) anonymous gap rc=$rc rows=$(awk 'NF{n++} END{print n+0}' "$W/l/ledger.tsv")"; tail -8 "$W/l.log"
fi

# (m) a WILDCARD cell -> REFUSED. A gap that matches a pattern of rows forgives rows nobody read.
g3="$(gapfile wild '{"gaps":[{"id":"wild","owner":"nobody","rule":"type","detail_contains":"expected number, got string","cells":["llm|cohere|*#response"],"why":"a wildcard entry, planted to prove the loader refuses a gap that could cover rows nobody has looked at"}]}')"
rc="$(run_gaps "$W/b-rec" "$W/m" "$W/b-rec/cells.json" "$g3")"
if [ "$rc" != 0 ] && grep -q 'carries a wildcard' "$W/m.log" \
   && [ "$(awk 'NF{n++} END{print n+0}' "$W/m/ledger.tsv")" = 0 ]; then
  say PASS "(m) a wildcard cell in a gap -> REFUSED at load, nothing judged"
else
  say FAIL "(m) wildcard gap rc=$rc rows=$(awk 'NF{n++} END{print n+0}' "$W/m/ledger.tsv")"; tail -8 "$W/m.log"
fi

# ── THE SIDE OF 2xx THE OUTCOME ASKED FOR ───────────────────────────────────────────────────────
# (p) a cell whose whole point is a REFUSAL — no credential at all — answered HTTP 200 with a
# happy-path body. Every byte of that body satisfies the dialect's RESPONSE schema, so a check that
# only asks "does this parse against the schema for the status that was sent" reports it green: the
# frame is fine, and the one thing the cell exists to prove is not.
cp -R "$FIX2" "$W/p-rec"
python3 - "$W/p-rec" <<'EOF'
import json, os, sys
rec = sys.argv[1]
ok, bad = "llm__gemini__gemini__request__ok_stream_array", "llm__gemini__gemini__request__unauthenticated"
with open(os.path.join(rec, "raw", ok, "body")) as f:
    body = json.dumps(json.load(f)[0], separators=(",", ":"))   # one valid GenerateContentResponse
with open(os.path.join(rec, "raw", bad, "body"), "w") as f:
    f.write(body)
with open(os.path.join(rec, "raw", bad, "headers"), "w") as f:
    f.write("HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ndate: Fri, 04 Sep 2026 20:35:30 GMT\r\n\r\n")
p = os.path.join(rec, "cells", bad + ".json")
with open(p) as f: cell = json.load(f)
cell["status"], cell["body"] = 200, {"json": json.loads(body)}
with open(p, "w") as f: json.dump(cell, f, separators=(",", ":"))
EOF
rc="$(run "$W/p-rec" "$W/p" "$FIX2/cells.json")"
rows="$(fail_rows "$W/p")"
if [ "$rc" != 0 ] && [ "$(count "$W/p" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|unauthenticated#response\t' <<<"$rows" && grep -q 'outcome.status' <<<"$rows"; then
  say PASS "(p) a refusal cell answered 2xx with a schema-clean success body -> RED on outcome.status"
else
  say FAIL "(p) refusal answered 2xx rc=$rc fails=$(count "$W/p" FAIL): $rows"
fi

# (q) the mirror: a HAPPY-PATH cell answered with a refusal. The body is a perfectly valid error
# envelope for the dialect, so the schema has nothing to say; what deviates is that an
# authenticated, in-scope, in-budget request was refused, and that must not read as green either.
cp -R "$FIX2" "$W/q-rec"
python3 - "$W/q-rec" <<'EOF'
import json, os, sys
rec = sys.argv[1]
ok, donor = "llm__gemini__gemini__request__ok_stream_array", "llm__gemini__gemini__request__over_budget"
for name in ("body", "headers"):
    with open(os.path.join(rec, "raw", donor, name), "rb") as f: data = f.read()
    with open(os.path.join(rec, "raw", ok, name), "wb") as f: f.write(data)
with open(os.path.join(rec, "cells", donor + ".json")) as f: dcell = json.load(f)
p = os.path.join(rec, "cells", ok + ".json")
with open(p) as f: cell = json.load(f)
cell["status"], cell["body"] = dcell["status"], dcell["body"]
with open(p, "w") as f: json.dump(cell, f, separators=(",", ":"))
EOF
rc="$(run "$W/q-rec" "$W/q" "$FIX2/cells.json")"
rows="$(fail_rows "$W/q")"
if [ "$rc" != 0 ] && [ "$(count "$W/q" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|ok_stream_array#response\t' <<<"$rows" && grep -q 'outcome.status' <<<"$rows"; then
  say PASS "(q) a happy-path cell answered with a schema-clean refusal -> RED on outcome.status"
else
  say FAIL "(q) happy path refused rc=$rc fails=$(count "$W/q" FAIL): $rows"
fi

# ── THE SPEC CACHE ITSELF ───────────────────────────────────────────────────────────────────────
# (n) a DRIFTED spec cache must refuse. The recording is the known-good fixture with ONE required
# member removed from the cohere response (`id`) — the pinned spec rejects that body, so the honest
# answer is RED. The cache handed to the run is a copy whose cohere document has been widened to
# accept it. If any copy of the spec inside a digest-named directory is trusted without being
# re-measured against that digest, this run comes back GREEN and the widened document — not the
# pinned one — is what "conformant" meant.
cp -R "$FIX" "$W/n-rec"
python3 - "$W/n-rec/raw/llm__cohere__cohere__request__ok/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); del d["id"]
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
# `drift <cache> <what>` widens cohere's ChatResponseV2 (drop `required`, open `usage`) in the
# named copies of the document inside the digest's own directory: `all` for every copy, `parsed`
# for the pre-parsed spec.parsed.json alone.
drift() {
  python3 - "$1" "$2" <<'EOF'
import glob, json, os, sys
d, what = glob.glob(os.path.join(sys.argv[1], "cohere", "*"))[0], sys.argv[2]
def widen(doc):
    s = doc["components"]["schemas"]["ChatResponseV2"]
    s["properties"]["usage"] = {}
    s["required"] = []
    return doc
p = os.path.join(d, "spec.parsed.json")
if not os.path.isfile(p):   # the pre-parse is gone as a concept; recreate it to prove it is not read
    import yaml
    src = os.path.join(d, "spec.yaml") if os.path.isfile(os.path.join(d, "spec.yaml")) else os.path.join(d, "spec.json")
    with open(src, "rb") as f:
        raw = f.read()
    try:
        doc = json.loads(raw)
    except ValueError:
        doc = yaml.load(raw, Loader=getattr(yaml, "CSafeLoader", yaml.SafeLoader))
    with open(p, "w") as f:
        json.dump(doc, f, separators=(",", ":"), default=str)
with open(p) as f:
    doc = json.load(f)
with open(p, "w") as f:
    json.dump(widen(doc), f, separators=(",", ":"))
if what == "all":
    q = os.path.join(d, "spec.json")
    if os.path.isfile(q):
        with open(q) as f: doc = json.load(f)
        with open(q, "w") as f: json.dump(widen(doc), f, separators=(",", ":"))
    q = os.path.join(d, "spec.yaml")
    if os.path.isfile(q):
        import yaml
        with open(q, "rb") as f: doc = yaml.load(f, Loader=getattr(yaml, "CSafeLoader", yaml.SafeLoader))
        with open(q, "w") as f: yaml.safe_dump(widen(doc), f)
EOF
}
SRC_CACHE="${BUSBAR_LLM_SPEC_CACHE:-$HOME/.cache/busbar-llm-specs}"

# (n) every copy drifted. `--no-vendor` so this is offline and so the answer comes from the cache
# check rather than from a re-download quietly repairing the drift mid-test.
cp -R "$SRC_CACHE" "$W/n-cache"; drift "$W/n-cache" all
RUN_ARGS="--no-vendor"
rc="$(BUSBAR_LLM_SPEC_CACHE="$W/n-cache" run "$W/n-rec" "$W/n")"
RUN_ARGS=""
if [ "$rc" != 0 ] && grep -qi 'drift' "$W/n.log" && [ "$(count "$W/n" PASS)" = 0 ]; then
  say PASS "(n) drifted spec cache -> RED, named as drift; nothing was judged against the widened document"
else
  say FAIL "(n) drifted spec cache rc=$rc pass=$(count "$W/n" PASS) fail=$(count "$W/n" FAIL) — a body the PINNED spec rejects was judged against a widened copy"; tail -8 "$W/n.log"
fi

# (o) ONLY the pre-parsed copy drifted, so the document that the digest measures is untouched and
# every cache check passes. The verdict must still be RED on the missing `id`: a pre-parse of a
# spec is not a spec, and nothing may reach the checker that was not measured against the pin.
cp -R "$W/n-rec" "$W/o-rec"
cp -R "$SRC_CACHE" "$W/o-cache"; drift "$W/o-cache" parsed
RUN_ARGS="--no-vendor"
rc="$(BUSBAR_LLM_SPEC_CACHE="$W/o-cache" run "$W/o-rec" "$W/o")"
RUN_ARGS=""
rows="$(fail_rows "$W/o")"
if [ "$rc" != 0 ] && [ "$(count "$W/o" FAIL)" = 1 ] && grep -q "required: missing property 'id'" <<<"$rows"; then
  say PASS "(o) a drifted PRE-PARSE of a verified spec is not consulted -> still RED on the missing member"
else
  say FAIL "(o) drifted pre-parse rc=$rc fails=$(count "$W/o" FAIL): $rows"; tail -8 "$W/o.log"
fi

echo
if [ "$fails" -eq 0 ]; then echo "llm-conformance selftest: GREEN (19/19)"; else echo "llm-conformance selftest: RED (${fails} failed)"; exit 1; fi
