#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Busbar Inc and contributors
#
# Prove the LLM spec conformance rig cannot pass vacuously, before any verdict from it is trusted.
# Every case goes through run.sh (vendor -> validate -> verdict), the real pipeline, with the tiny
# tracked fixture under fixtures/selftest-recording (three 1.5.5 cells that validate cleanly):
#
#   (a) the known-good fixture                       -> GREEN, every owed row PASS
#   (b) one response field's TYPE mutated            -> RED, exactly one FAIL, naming the pointer
#   (c) one SSE event field's TYPE mutated           -> RED, exactly one FAIL, naming sse[N]:/pointer
#   (d) one REQUEST field's TYPE mutated             -> RED, exactly one FAIL, on the #request row
#   (e) an empty recording directory                 -> RED, the vacuous-run ("zero rows") verdict
#   (f) a cell present in cells.json but not recorded -> a named SKIP, never a PASS; verdict still
#       GREEN on the rows that exist (the gap is visible, not fatal by itself)
#
# A second tiny tracked fixture, fixtures/selftest-errors-recording (regenerated by
# fixtures/gen-errors-fixture.py; six gemini cells: ok_stream_array + all five error outcomes),
# proves two more things the first fixture does not exercise:
#
#   (g) gemini `ok_stream_array` (a stream requested WITHOUT ?alt=sse; per the Gemini API this is
#       served as a JSON ARRAY of GenerateContentResponse objects, not one object and not SSE)
#       -> GREEN: the array is judged element-by-element against GenerateContentResponse instead of
#          being rejected outright as "expected object, got array"
#   (h) one element of that array given a malformed field                -> RED, exactly one FAIL
#       naming the array index (e.g. `/1/modelVersion`)
#   (i) every error outcome (malformed, unauthenticated, out_of_scope, over_budget, upstream_down)
#       -> GREEN as shipped: each error body is something the SUCCESS schema would reject outright
#          (closed object, no "error" property), so a PASS here is proof the checker judged it
#          against the dialect's ERROR envelope, not the success schema
#
# A third fixture, fixtures/selftest-gap-recording (one recorded cell: the ingress-Anthropic
# cross-protocol stream, which carries the `ping` frame Anthropic documents and its published
# MessageStreamEvent union omits), holds the NAMED CONFORMANCE GAP register to the four things it
# claims — a register that cannot do these is a way to make a failure disappear:
#
#   (j) the registered gap MATCHES        -> the row is classified `gap`: its own column, out of the
#       owed set, counted by the verdict, and NEVER a pass. The entry's own `named-gap|<id>` row is
#       PASS because it fired.
#   (k) a registered gap that never fires -> RED. An unused gap is a lie.
#   (l) a STALE pin (the entry's spec digest is not what spec-digests.tsv pins today) -> RED, and it
#       forgives nothing while stale: the row it used to cover goes back to FAIL.
#   (m) zero rows                         -> RED. The register cannot make a vacuous run green.
#
# Needs the vendored specs (run.sh vendors them; cached by digest, so this is offline after once).
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
FIX="${here}/fixtures/selftest-recording"
FIX2="${here}/fixtures/selftest-errors-recording"
FIX3="${here}/fixtures/selftest-gap-recording"
W="$(mktemp -d "${TMPDIR:-/tmp}/llm-conformance-selftest.XXXXXX")"
trap 'rm -rf "$W"' EXIT
fails=0
say() { printf '%s  %s\n' "$1" "$2"; [ "$1" = PASS ] || fails=$((fails+1)); }
run() {  # run <recording> <out> [cells.json] [named-gaps.json] -> rc
  local cells="${3:-$1/cells.json}" gaps="${4:-${here}/named-gaps.json}"
  bash "${here}/run.sh" --recording "$1" --out "$2" --cells "$cells" --named-gaps "$gaps" >"$2.log" 2>&1; echo $?
}
count() { awk -F'\t' -v s="$2" '$2==s{n++} END{print n+0}' "$1/ledger.tsv"; }
fail_rows() { awk -F'\t' '$2=="FAIL"{print $1"\t"$4}' "$1/ledger.tsv"; }

# (a) known-good
rc="$(run "$FIX" "$W/a")"
if [ "$rc" = 0 ] && [ "$(count "$W/a" PASS)" = 6 ] && [ "$(count "$W/a" FAIL)" = 0 ] && [ "$(count "$W/a" SKIP)" = 0 ]; then
  say PASS "(a) known-good fixture -> GREEN, 6/6 rows PASS"
else
  say FAIL "(a) known-good fixture rc=$rc pass=$(count "$W/a" PASS) fail=$(count "$W/a" FAIL) skip=$(count "$W/a" SKIP)"; tail -20 "$W/a.log"
fi

# (b) mutate a response field's type: cohere usage.tokens.input_tokens integer -> string
cp -R "$FIX" "$W/b-rec"
python3 - "$W/b-rec/raw/llm__cohere__cohere__request__ok/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d["usage"]["tokens"]["input_tokens"]="11"
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
rc="$(run "$W/b-rec" "$W/b")"
rows="$(fail_rows "$W/b")"
if [ "$rc" != 0 ] && [ "$(count "$W/b" FAIL)" = 1 ] && grep -q $'^llm|cohere|cohere|request|ok#response\t' <<<"$rows" && grep -q '/usage/tokens/input_tokens type' <<<"$rows"; then
  say PASS "(b) one mutated response type -> RED, exactly one FAIL naming /usage/tokens/input_tokens"
else
  say FAIL "(b) mutated response rc=$rc fails=$(count "$W/b" FAIL): $rows"
fi

# (c) mutate one SSE event: cohere content-delta index integer -> string
cp -R "$FIX" "$W/c-rec"
python3 - "$W/c-rec/raw/llm__cohere__cohere__request__ok_stream/body" <<'EOF'
import sys
p=sys.argv[1]; s=open(p).read()
assert '"index":0' in s
open(p,"w").write(s.replace('"index":0','"index":"0"',1))
EOF
rc="$(run "$W/c-rec" "$W/c")"
rows="$(fail_rows "$W/c")"
if [ "$rc" != 0 ] && [ "$(count "$W/c" FAIL)" = 1 ] && grep -q $'^llm|cohere|cohere|request|ok_stream#response\t' <<<"$rows" && grep -q 'sse\[1\]:/index type' <<<"$rows"; then
  say PASS "(c) one mutated SSE event -> RED, exactly one FAIL naming sse[1]:/index"
else
  say FAIL "(c) mutated SSE rc=$rc fails=$(count "$W/c" FAIL): $rows"
fi

# (d) mutate the REQUEST: gemini contents array -> string
cp -R "$FIX" "$W/d-rec"
printf '%s' '{"contents":"ping"}' >"$W/d-rec/raw/llm__gemini__gemini__request__ok/request.body"
rc="$(run "$W/d-rec" "$W/d")"
rows="$(fail_rows "$W/d")"
if [ "$rc" != 0 ] && [ "$(count "$W/d" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|ok#request\t' <<<"$rows" && grep -q '/contents type' <<<"$rows"; then
  say PASS "(d) one mutated request type -> RED, exactly one FAIL on the #request row naming /contents"
else
  say FAIL "(d) mutated request rc=$rc fails=$(count "$W/d" FAIL): $rows"
fi

# (e) empty recording -> vacuous RED
mkdir -p "$W/e-rec"
rc="$(run "$W/e-rec" "$W/e" "$FIX/cells.json")"
if [ "$rc" != 0 ] && [ "$(awk 'NF{n++} END{print n+0}' "$W/e/ledger.tsv")" = 0 ] && grep -q 'VACUOUS RUN' "$W/e.log"; then
  say PASS "(e) empty recording -> RED, vacuous run (zero rows)"
else
  say FAIL "(e) empty recording rc=$rc rows=$(awk 'NF{n++} END{print n+0}' "$W/e/ledger.tsv")"; tail -5 "$W/e.log"
fi

# (f) a cell in the universe that the recording lacks -> named SKIP, not a PASS
cp -R "$FIX" "$W/f-rec"
rm "$W/f-rec/cells/llm__gemini__gemini__request__ok.json"
rc="$(run "$W/f-rec" "$W/f")"
if [ "$rc" = 0 ] && [ "$(count "$W/f" SKIP)" = 2 ] && [ "$(count "$W/f" PASS)" = 4 ] && grep -q 'named gap' "$W/f/ledger.tsv" && [ "$(wc -l <"$W/f/owed-gaps.txt" | tr -d ' ')" = 2 ]; then
  say PASS "(f) unrecorded cell -> 2 named SKIP rows (request+response), listed as gaps, never PASS"
else
  say FAIL "(f) unrecorded cell rc=$rc pass=$(count "$W/f" PASS) skip=$(count "$W/f" SKIP) gaps=$(wc -l <"$W/f/owed-gaps.txt" 2>/dev/null | tr -d ' ')"; tail -8 "$W/f.log"
fi

# (g) known-good errors fixture: ok_stream_array (valid 2-element array) + all 5 error outcomes
rc="$(run "$FIX2" "$W/g" "$FIX2/cells.json")"
if [ "$rc" = 0 ] && [ "$(count "$W/g" PASS)" = 11 ] && [ "$(count "$W/g" FAIL)" = 0 ] && [ "$(count "$W/g" SKIP)" = 0 ]; then
  say PASS "(g) known-good errors fixture -> GREEN, 11/11 rows PASS (ok_stream_array + 5 error outcomes)"
else
  say FAIL "(g) known-good errors fixture rc=$rc pass=$(count "$W/g" PASS) fail=$(count "$W/g" FAIL) skip=$(count "$W/g" SKIP)"; tail -20 "$W/g.log"
fi

# (h) mutate ONE element (index 1) of the ok_stream_array body: modelVersion string -> integer
cp -R "$FIX2" "$W/h-rec"
python3 - "$W/h-rec/raw/llm__gemini__gemini__request__ok_stream_array/body" <<'EOF'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d[1]["modelVersion"]=12345
open(p,"w").write(json.dumps(d,separators=(",",":")))
EOF
rc="$(run "$W/h-rec" "$W/h" "$FIX2/cells.json")"
rows="$(fail_rows "$W/h")"
if [ "$rc" != 0 ] && [ "$(count "$W/h" FAIL)" = 1 ] && grep -q $'^llm|gemini|gemini|request|ok_stream_array#response\t' <<<"$rows" && grep -q '/1/modelVersion type' <<<"$rows"; then
  say PASS "(h) one malformed array element -> RED, exactly one FAIL naming /1/modelVersion"
else
  say FAIL "(h) malformed array element rc=$rc fails=$(count "$W/h" FAIL): $rows"
fi

# ── the named conformance gap register ──────────────────────────────────────────────────────────
# The four cases below drive the REAL register through run.sh; (k) and (l) mutate a COPY of it, so
# what is proven is the mechanism, not a test-only path.

# (j) the registered `ping` gap matches -> the row is a GAP, not a PASS and not a FAIL
rc="$(run "$FIX3" "$W/j")"
gap_row='llm|anthropic|openai|request|ok_stream#response'
if [ "$rc" = 0 ] && [ "$(count "$W/j" GAP)" = 1 ] && [ "$(count "$W/j" FAIL)" = 0 ] \
   && awk -F'\t' -v i="$gap_row" '$1==i && $2=="GAP"{f=1} END{exit !f}' "$W/j/ledger.tsv" \
   && grep -q $'^named-gap|G-1 anthropic ping\tPASS' "$W/j/ledger.tsv" \
   && grep -q 'named conformance gaps: 1' "$W/j.log"; then
  say PASS "(j) a matching named gap -> row class gap, its own column, counted by the verdict, never a pass"
else
  say FAIL "(j) matching gap rc=$rc gap=$(count "$W/j" GAP) fail=$(count "$W/j" FAIL) pass=$(count "$W/j" PASS)"; tail -12 "$W/j.log"
fi

# (k) a registered gap that never fires -> RED (an unused gap is a lie)
python3 - "${here}/named-gaps.json" "$W/gaps-unused.json" <<'EOF'
import copy, json, sys
d = json.load(open(sys.argv[1]))
ghost = copy.deepcopy(d["gaps"][0])
ghost["id"] = "G-TEST never fires"
# In scope (it names the same cells, so the run owes it a row) but it forgives a violation no row
# produces — the shape of an entry the product outgrew.
ghost["violation"]["detail_contains"] = "'type': 'a-frame-nothing-emits' is not one of"
d["gaps"].append(ghost)
json.dump(d, open(sys.argv[2], "w"), indent=1)
EOF
rc="$(run "$FIX3" "$W/k" "$FIX3/cells.json" "$W/gaps-unused.json")"
if [ "$rc" != 0 ] && [ "$(count "$W/k" GAP)" = 1 ] \
   && grep -q $'^named-gap|G-TEST never fires\tFAIL' "$W/k/ledger.tsv" \
   && grep -q 'NEVER FIRED' "$W/k/ledger.tsv"; then
  say PASS "(k) a registered gap that never fired -> RED, named as its own failing row"
else
  say FAIL "(k) unused gap rc=$rc gap=$(count "$W/k" GAP) fail=$(count "$W/k" FAIL)"; tail -12 "$W/k.log"
fi

# (l) the pinned spec digest moved -> the entry is STALE: RED, and it forgives nothing meanwhile
python3 - "${here}/named-gaps.json" "$W/gaps-stale.json" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
old = d["gaps"][0]["spec_digest"]
stale = ("0" * 8) + old[8:]          # a digest spec-digests.tsv does not pin
d["gaps"][0]["spec_digest"] = stale
d["gaps"][0]["review_at"] = "spec-digest:" + stale
json.dump(d, open(sys.argv[2], "w"), indent=1)
EOF
rc="$(run "$FIX3" "$W/l" "$FIX3/cells.json" "$W/gaps-stale.json")"
if [ "$rc" != 0 ] && [ "$(count "$W/l" GAP)" = 0 ] \
   && awk -F'\t' -v i="$gap_row" '$1==i && $2=="FAIL"{f=1} END{exit !f}' "$W/l/ledger.tsv" \
   && grep -q 'STALE' "$W/l/ledger.tsv"; then
  say PASS "(l) a stale spec pin -> RED, and the row it covered goes back to FAIL until re-confirmed"
else
  say FAIL "(l) stale pin rc=$rc gap=$(count "$W/l" GAP) fail=$(count "$W/l" FAIL)"; tail -12 "$W/l.log"
fi

# (m) zero rows with the register in play -> still the vacuous-run RED
mkdir -p "$W/m-rec"
rc="$(run "$W/m-rec" "$W/m" "$FIX3/cells.json")"
if [ "$rc" != 0 ] && [ "$(count "$W/m" GAP)" = 0 ] && grep -qE 'VACUOUS RUN|DID NOT RUN' "$W/m.log"; then
  say PASS "(m) zero rows -> RED; a register cannot make a run that judged nothing green"
else
  say FAIL "(m) zero rows with register rc=$rc rows=$(awk 'NF{n++} END{print n+0}' "$W/m/ledger.tsv")"; tail -8 "$W/m.log"
fi

echo
if [ "$fails" -eq 0 ]; then echo "llm-conformance selftest: GREEN (12/12)"; else echo "llm-conformance selftest: RED (${fails} failed)"; exit 1; fi
